### ISSUE TITLE
Switch v0.9.1 release tag from 612083f to 54611f2

### ISSUE THREAD

**Issue by MailYouLater** [LibreHardwareMonitor/LibreHardwareMonitor#1000]
The current ([v0.9.1](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/v0.9.1)) release is tagged on the wrong commit.  The release tag currently points to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/612083fabeea6aaae709591601451d9793ffce78, which contains a mistake in the contents which would break the build, and "does not belong to any branch on this repository" (dangling commit).  The release tag for [v0.9.1](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.9.1) should be moved to the functionally equivalent (but not build-breaking) commit that is included in the repo's commit history: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/54611f2146f21abca6932f5a29e3c025d9c1fa28.

![This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.](https://user-images.githubusercontent.com/1279475/223596662-69caf880-5110-4dc0-bf05-1702258ce8b9.png)
![Screenshot of git log showing the current status of both commits](https://user-images.githubusercontent.com/1279475/223519902-b0f95374-6e62-4c00-a37d-81368866ec76.png)

**Comment by PhyxionNL** [comment]
I see, but there doesn't seem to be an easy way to change it, so I'll leave it as-is.
