### ISSUE TITLE
Gigabyte X570 Aorus Pro and other Aorus Boards no Control for Fans on IT8792E

### ISSUE THREAD

**Issue by Sn00kiT** [LibreHardwareMonitor/LibreHardwareMonitor#1009]
i know it´s a old problem but there is still no fix for it. 
The problem is that the mainboard has 2 ITE Chips (IT8688E&ITE879E) and the second one does not work. Fans are recognized but the Control does not Work and the sensor for it neither.
HWInfo shows it correctly and the fans are adjustable by Gigabyte SIV.

If have seen that there is a fork. Can you maybe merge this into LHM?
https://github.com/frankcrawford/it87/tree/master/Sensors%20configs

![2023-03-10 15_50_44-HWiNFO64 v7 40-5000 - Sensorstatus](https://user-images.githubusercontent.com/77878228/224480126-156fdb06-96ed-4702-871b-07f4557ec274.png)
![2023-03-11 11_49_11-Fan Control V149 (userConfig json)](https://user-images.githubusercontent.com/77878228/224480128-8d3c2510-2a9e-4f54-9a09-514ca6d1ac86.png)

**Comment by bearlygeek** [comment]
+1 on this request - I have the X570S Pro AX 1.1

**Comment by PhyxionNL** [comment]
See #731.
