### ISSUE TITLE
The L1 cache in SMBios is fetched incorrectly

### ISSUE THREAD

**Issue by daihengfei** [LibreHardwareMonitor/LibreHardwareMonitor#1012]
![image](https://user-images.githubusercontent.com/33371442/224928645-13e228d3-8e43-43a9-819f-6e0ae3645360.png)
As shown in the figure, the program does not obtain the L1 data cache, and the L2 cache way is not obtained

**Comment by PhyxionNL** [comment]
Then it's wrongly reported by BIOS, can't do anything with this here.
