### ISSUE TITLE
The CPU temperatures and clocks are missing 

### ISSUE THREAD

**Issue by HelinWang0721** [LibreHardwareMonitor/LibreHardwareMonitor#1016]
After I reinstall the windows 11 Pro (22H1), I download the LHM and see that all sensors of MB are missing such temperatures, clock, fan speed, etc.. I tried many possible solutions but no luck. Does someone has same issues? 
![image](https://user-images.githubusercontent.com/44213774/225828179-aa4591b5-b3fe-4ba7-bb36-562b282b5007.png)

**Comment by phl23** [comment]
Same for me. Since the last Windows 11 Update I'm missing CPU temp, clocks and all mainboard sensors.

**Comment by HelinWang0721** [comment]
> 

You accutally correct, used repair tool for .net framework and it works immediately
