### ISSUE TITLE
"Max CPU/Thread Usage" equivalent

### ISSUE THREAD

**Issue by mr-swaz** [LibreHardwareMonitor/LibreHardwareMonitor#1019]
Hi, would it be possible to add an equivalent of HWiNFO's "Max CPU/Thread Usage"?
It's described as "maximum value of all current core/thread utilizations".
It's pretty useful to detect CPU bottlenecks, without having to compare all the maximum values of each thread.

![max_cpu_thread_usage](https://user-images.githubusercontent.com/45634764/226129298-aa1bb514-df62-4449-84f1-9d0295d141d8.png)

**Comment by MattLichter** [comment]
I would really like this too.  So much so that I already modified the source in my own fork.  Seeing as there is some interest, I'll prepare a PR and see what the devs have to say.

**Comment by mr-swaz** [comment]
> I would really like this too. So much so that I already modified the source in my own fork. Seeing as there is some interest, I'll prepare a PR and see what the devs have to say.

Thanks @MattLichter, but I see that you added the new virtual sensor to GenericCpu.cs only. In fact it doesn't show up using an Intel CPU. Would it be possible to add it to IntelCpu.cs and Amd*.cs as well?

**Comment by MattLichter** [comment]
@mr-swaz GenericCpu is the base class of the IntelCpu and Amd*Cpu classes.  By adding the feature to GenericCpu I have added it to every CPU class.

This feature is currently implemented in `master` but has not be released in a tagged version yet.  It will be available in the version after `0.9.2`.  Perhaps that is why you are not seeing the new behavior?
