### ISSUE TITLE
Sensor ITE IT8686E on a Gigabyte X370 Gaming K7 are not read correctly and no Fancontrol possible

### ISSUE THREAD

**Issue by KillerGER87** [LibreHardwareMonitor/LibreHardwareMonitor#1030]
Sensors on a Gigabyte X370 Gaming K7 are shown but i can't control any of my Fanspeeds 
Controler 1: ITE IT8686E does not even show the Controle row
Controler 2 ITE IT8791E/IT8792E does show the Controle row but it dosent function
[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/11068646/LibreHardwareMonitor.Report.txt)
![libre](https://user-images.githubusercontent.com/128897429/227741044-d96e5f7b-eaa4-4e47-93d6-07701776d81b.JPG)

If anyone can help it would be much appreciate

**Comment by BenNeumeister** [comment]
You need to add the 'control' functions into the configs for your board.
Adding those might fix the secondaries too.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs#L1207


Example;
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/SuperIOHardware.cs#L1252

**Comment by KillerGER87** [comment]
Thanks for your Input.
The only Problem is that i have no idea how to do that. I have no knowlege in programming.
 So can you are anyone else do that for me?

**Comment by BenNeumeister** [comment]
> Thanks for your Input. The only Problem is that i have no idea how to do that. I have no knowlege in programming. So can you are anyone else do that for me?

The problem is that you will need to compile it locally anyway in order to test update, so why not learn how to do it?

Get VS2022 from here (its free);
https://visualstudio.microsoft.com/downloads/

Install the .NET framework.
You will need the net4.x, 6 and 7 runtimes.

Download GitDesktop, do a clone of this repo and give it ago.
Once it working, do a PR.

**Comment by KillerGER87** [comment]
Thanks a lot! It does Controle know the first 5 Fans on the first Controler but the second one does still nothing. My question is now how can i submit my changes to here?

**Comment by BenNeumeister** [comment]
Great it worked, the 2nd gigabyte controller was just added so might be some bugs in some instances.
Interesting a board so old has 8 fan controllers.

From GitDesktop you should be able to raise a PR against the main repo.
