### ISSUE TITLE
lpmi NullReferenceException

### ISSUE THREAD

**Issue by Rem0o** [LibreHardwareMonitor/LibreHardwareMonitor#1054]
4/17/2023 7:10:05 PM: System.NullReferenceException: Object reference not set to an instance of an object.
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Ipmi.Update(StringBuilder stringBuilder) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Ipmi.cs:line 190

See https://github.com/Rem0o/FanControl.Releases/issues/1723

I believe @lukefor created that class. 

There ain't that many vars that can go wrong near line 190.
All I see is 
```c#
 _voltages.Add(RawToFloat(reading[1], sdr));

// _voltages is a read-only list
// reading is an array of byte, which would explode earlier if it was null
// sdr is a struct, which can't be null. 
```

**Comment by PhyxionNL** [comment]
This is indeed a very strange line for this error. Perhaps @tscislowski can give the build from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1055 a try.

**Comment by PhyxionNL** [comment]
Perhaps @tscislowski can give the build from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1055 a try.

**Comment by Rem0o** [comment]
@tscislowski 
Take LibreHardwareMonitor-net472 from
 https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/4736688928
 
Launch LibreHardwareMonitor itself, or take LibreHardwareMonitorLib.dll, and replace the one in FanControl with it.

**Comment by doolbneerg** [comment]
I just hit this myself.  Looking at the code, it looks like there are some order of operation issues.  The library expects to be able to update the sensors before allocating the memory for the sensors. However, it also needs some other pieces to be initialized for it to pull the SDR. I am working through some changes now.

**Comment by Abiodun070** [comment]
_voltages.Add(RawToFloat(reading[1], sdr));

// _voltages is a read-only list
// reading is an array of byte, which would explode earlier if it was null
// sdr is a struct, which can't be null.
