### ISSUE TITLE
AMD Radeon RX 7000 , GPU Package always 0W + solution

### ISSUE THREAD

**Issue by 1usmus** [LibreHardwareMonitor/LibreHardwareMonitor#1074]
There is no GPUPower sensor for this series, instead there is GPUTotalBoardPower.

**Comment by PhyxionNL** [comment]
Can you submit a PR? Thanks.

**Comment by 1usmus** [comment]
> Can you submit a PR? Thanks.

GetPMLog(logDataOutput, AtiAdlxx.ADLSensorType.PMLOG_ASIC_POWER, _powerTotal, reset: false);

Find this line in the project, it is not valid for RX 7000, use the following instead:

GetPMLog(logDataOutput, **73**, _powerTotal, reset: false);

**73** is the index of the undocumented TOTAL BOARD POWER sensor for the RX 7000

:)

**Comment by NecromancerForLife** [comment]
Hi i have a PR here https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1123 @1usmus @PhyxionNL but the readings on my 7900 xt seem way too high 570W maximum. I do not know what correction is to apply.

**Comment by 1usmus** [comment]
> Hi i have a PR here #1123 @1usmus @PhyxionNL but the readings on my 7900 xt seem way too high 570W maximum. I do not know what correction is to apply.

I get the exact same peak values around 3000-3500MHz for memory. So it can be written off as a calculation error in SMU. Although I can believe in peak 570W, with monitoring via 12V line something similar can be observed.

**Comment by NecromancerForLife** [comment]
> > Hi i have a PR here #1123 @1usmus @PhyxionNL but the readings on my 7900 xt seem way too high 570W maximum. I do not know what correction is to apply.
> 
> I get the exact same peak values around 3000-3500MHz for memory. So it can be written off as a calculation error in SMU. Although I can believe in peak 570W, with monitoring via 12V line something similar can be observed.

Hmm ok, well since No other Sensor seems to Work, this should do it. Yet i find It strangely high for a 300w Maximum graphics Card. Hopefully the pr helps

**Comment by 1usmus** [comment]
> Hmm ok, well since No other Sensor seems to Work, this should do it. Yet i find It strangely high for a 300w Maximum graphics Card. Hopefully the pr helps

AMD's website says 750 W minimum PSU Recommendation for a reason, the peaks have always been there.

**Comment by NecromancerForLife** [comment]
OK i remember your memory Timings Programm. i think you know much better than me what you are talking about.

**Comment by NecromancerForLife** [comment]
PR is in master now. Shall we close the topic?
