### ISSUE TITLE
Invisible driver file .sys

### ISSUE THREAD

**Issue by ios1ph** [LibreHardwareMonitor/LibreHardwareMonitor#1075]
When computer.Open() there is driver file created appname.sys in exe directory.
There was a method in old HardwareMonitor to extract driver in temp folder which was better.
It is not cool when driver file extracted in exe path when you have portable app with single exe.
Could you add possibility to hide driver or choose directory to extract driver?
I mean I have already changed and created my own dll. But would be cool if you make changes here too, cuz I want to be updated using nuget as sson as new version comes out, to not every time update code by myself.

**Comment by PhyxionNL** [comment]
No, it works fine in portable scenarios as the sys file should be cleaned after use.

**Comment by ios1ph** [comment]
It visible. When you run exe app from your desktop and sys file creates on you desktop lol.
