### ISSUE TITLE
Values in the tray icon: the font color has to be customizable

### ISSUE THREAD

**Issue by VioletGiraffe** [LibreHardwareMonitor/LibreHardwareMonitor#11]
Since the task bars are most often of dark color, the black readings are unreadable. Example:
![image](https://user-images.githubusercontent.com/1175926/30519378-c2357368-9b9d-11e7-9f48-f121046d22b9.png)

There is the graphics card temperature value just to the right of the arrow, where the tray region begins. But you'll have to take my word on that ;)

The text color has to be customizable; at the very least a choice between black and white would suffice, and white should be the default.

**Comment by Maddimax** [comment]
You can right click the tray icon and select "Change color" to change the color ;)

**Comment by VioletGiraffe** [comment]
Hmm. That's good, thanks. A bit counter-intuitive as I was looking for it in the application settings.
Still, wouldn't white be a more logical choice for the default color?

**Comment by Maddimax** [comment]
I would agree since a black taskbar is the default on Windows 10. Maybe it should default based on the windows version.

**Comment by VioletGiraffe** [comment]
The last desktop Windows OS with the light-colored default task bar was Win 2k. It's pretty safe to disregard that possibility, in my opinion :)
