### ISSUE TITLE
latest release on github 'release' page is stuck at 0.8 => creates false impression of 'dead' project

### ISSUE THREAD

**Issue by mi-hol** [LibreHardwareMonitor/LibreHardwareMonitor#110]
Latest release directly downloadable from GitHub is from 6 Nov 2016 version 0.8.0 !

As a result GitHub feature 'watch releases' doesn't alert potential users and creates the false impression of a 'dead' project.

**Comment by Phyxion** [comment]
I have removed all releases from GitHub and will try to get AppVeyor working again so executables can be downloaded again.

**Comment by mi-hol** [comment]
@Phyxion it seems the issue is still open. How about reopening it?

**Comment by Phyxion** [comment]
No, there are no more releases listed. Latest builds are done through AppVeyor and linked on main page as such.

**Comment by Phyxion** [comment]
There are no more releases listed, so this issue is no longer valid. AppVeyor is working again so the latest builds can be downloaded through it (and they're linked on the main page as such).
