### ISSUE TITLE
CPU temperature wrong with dll compared to OpenHardwareMonitor

### ISSUE THREAD

**Issue by risikoruk** [LibreHardwareMonitor/LibreHardwareMonitor#115]
By integrating this DLL in a project where the old OHW dll was inserted, I'm now getting the right temperatures of 9xxx series intel CPUs, but the temperature for older ones is now null on every sensor

Any idea why?

**Comment by informatorius** [comment]
Post your older ones specs

**Comment by Phyxion** [comment]
Closing due to lack of specs or reports.
