### ISSUE TITLE
System.ArgumentOutOfRangeException with BIOS Date Parsing

### ISSUE THREAD

**Issue by BoiHanny** [LibreHardwareMonitor/LibreHardwareMonitor#1150]
# Description
While using LibreHardwareMonitor, someone encountered a System.ArgumentOutOfRangeException mentions explicitly that the "Year, Month, and Day parameters describe an un-representable DateTime." 

This issue seems similar to a closed issue ([#297](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/297)), which was apparently fixed in a later update (#432). However, the problem still persists in our case.

# Details
Here is the exact stack trace of the error:
`System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at LibreHardwareMonitor.Hardware.BiosInformation.GetDate(String date)`

**Comment by MySelections** [comment]
Waiting for the author's reply (#1248)

**Comment by MySelections** [comment]
You could give this a shot to see if it’s sorted out.

**Comment by PhyxionNL** [comment]
Closing.
