### ISSUE TITLE
Weird Version Number shown in "About"-dialog

### ISSUE THREAD

**Issue by pr030880** [LibreHardwareMonitor/LibreHardwareMonitor#1227]
When you choose "Help"->"About" it shows:
Version 0.9.3+67ff1135158c669fab2... ... ...

Is this correct? The part after Version 0.9.3?![About_Version_0.9.3.jpg](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/123210846/646ccd22-da1d-4b57-9632-59e8096e1810)

**Comment by PhyxionNL** [comment]
Yes, it's the git commit hash.
