### ISSUE TITLE
Strange random string in "Product-Version" since 0.3.9

### ISSUE THREAD

**Issue by Klaus-Aschaber** [LibreHardwareMonitor/LibreHardwareMonitor#1229]
I created a powershell script for my RMM-System that monitors the temperatures. It also reads the Product-Version out of the "LibreHardwareMonitorLib.dll" and compares it with the current version on github.

If there is a newer version available, the script will automatically update LHM.

However since the last Update (0.3.9) there is some some string, always starting with "+" behind the "real" version number.

The same thing applies to the version-number in the LHM.exe.

Of cause it can be easily mitigated by modifying the version-string, but I am wondering if this is expected, or some kind of bug.

For example if you try to parse the version to "System.Version" in PowerShell; using [System.Version]::Parse($version) you will get an exception .

Code for recreation:

$LHMLibDll = Join-Path $config.LHMDir -ChildPath '\LibreHardwareMonitorLib.dll' #edit to fit your env.
((Get-ItemProperty -Path $LHMLibDll).VersionInfo.ProductVersion) #will display the strange version number.
[System.Version]::Parse(((Get-ItemProperty -Path $LHMLibDll).VersionInfo.ProductVersion)) #will throw exception on version 0.3.9, but not on 0.9.2

<img width="265" alt="2024-01-04 10_41_18-Eigenschaften von LibreHardwareMonitor exe" src="https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/140325376/2cc01937-8a44-46ef-a4c5-f565d2eb64d0">
<img width="266" alt="2024-01-04 10_39_13-Eigenschaften von LibreHardwareMonitorLib dll" src="https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/140325376/8621f3f8-af88-42e4-a05d-63b03a19e153">
<img width="893" alt="2024-01-04 10_58_53-● $LHMLibDll = Join-Path $config LHMDir -C • Untitled-1 - Powershell (Arbeitsber" src="https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/140325376/d8034186-9011-4614-8731-ffc393a0f523">
<img width="406" alt="2024-01-04 10_49_39-Devices - Datto RMM – Mozilla Firefox" src="https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/140325376/2c0b8c59-3b58-4104-add9-262b0d714d30">

**Comment by PhyxionNL** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/1227
