### ISSUE TITLE
CPU and GPU Power usage aren't here, using CS program

### ISSUE THREAD

**Issue by 2DotWasHere** [LibreHardwareMonitor/LibreHardwareMonitor#1240]
I've create an CS program to track CPU and GPU power usage, using example from readme, but for some reason it won't report those stats, even tho i have them in official `LibreHardwareMonitor.exe`.

Here's my code: [link](https://gist.github.com/2DotWasHere/367ab142cbbafd313b2b4dc9e65c7e23)

in app.manifest i have:
```.manifest
<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />/>
```

## So do i missed anything that can block me from getting those stats?

**Comment by 2DotWasHere** [comment]
i found the issue, you need to build your program for x64

**Comment by yarodevuci** [comment]
@DoubleIsNaN did not help for me
