### ISSUE TITLE
Incorrect GPU Load and Core Frequency values (Radeon RX 7900XT)

### ISSUE THREAD

**Issue by Schuischta** [LibreHardwareMonitor/LibreHardwareMonitor#1285]
I discovered that the GPU Load and Core Frequency on the RX 7900 XT (and probably other newer GPU's too) jumps randomly up and down, so it doesn't show the correct values. I saw that while I was testing my little widget-like performance monitor. -> [https://github.com/schuischta/systemloadtracker](url)

**Comment by pepitomiaumiau** [comment]
Yup, can confirm. The values for my 7900XT are absolutely all over the place, most of the time jumping from 0% to 100% out of nowhere. 

The wrong values are coming from LibreHardwareMonitor, you can use it separately to test it.

**Comment by epinter** [comment]
"Powers/GPU Package" has a huge variation, while amd overlay and GPU-z stays stable at 113w-116w for example, librehardwaremonitor jumps from 60 to 150 and back to lower than 100w in a second. Same happens with "Load/GPU Core" and "Load/GPU Memory".  "Clocks/GPU Core" also has a variation, but looks different.
