### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by sebastian-dev** [LibreHardwareMonitor/LibreHardwareMonitor#133]
https://ci.appveyor.com/project/LibreHardwareMonitor/librehardwaremonitor/build/artifacts
is not working with the new project structure maybe appveyor.yml need some fixes

**Comment by chtof** [comment]
It should explain why I do not longer find `bin%2FRelease.zip` on https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.

**Comment by fboldog** [comment]
Interesting, build from my last development branch had a proper zip:
https://ci.appveyor.com/project/fboldog/librehardwaremonitor/build/artifacts

**Comment by Eno77** [comment]
Console says:

```
Collecting artifacts...
No artifacts found matching 'Bin\Release' path
```

Perhaps the zip file is not in correct path anymore or something?

**Comment by Phyxion** [comment]
Took some time and testing but it's creating a release again.

**Comment by Phyxion** [comment]
Took some time and testing but it's uploading artifacts again.
