### ISSUE TITLE
Recognition RAM by model

### ISSUE THREAD

**Issue by xgrommx** [LibreHardwareMonitor/LibreHardwareMonitor#1333]
Hello, would it be possible to recognize RAM by model, not as general memory. 
I mean for example in my pc I have 2 RAM Kingston FURY but this app recognize it as general memory and show total memory with sum of 2 my RAM, but I want to see 2 RAM with names and separated size of memory.

**Comment by CopiiDeco** [comment]
Technically it should be possible to find the info but the info displayed is not at the memory stick level but handles the memory info as a whole.

**Comment by PhyxionNL** [comment]
Can be taken along with #395.
