### ISSUE TITLE
CPU load and CPU temperature not calculated on ARM64 machine

### ISSUE THREAD

**Issue by AnushaG2201** [LibreHardwareMonitor/LibreHardwareMonitor#1373]
CPU load and temperature are not captured in ARM machine with Snapdragon (TM) 8cx Gen 3 @ 3.0 GHz processor.
When run as an application(GUI), it displays all the cpu sensors. But when used programmatically, it is not able to detect all the cpu sensors.

Output when ran the sample code shared,
![image](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/76487202/7403c12f-d55a-4514-8589-4e0cf4ce3491)

Output from GUI(looks like this runs as x64)
![image](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/76487202/541bdf17-c0f2-4379-be89-7f5fcd9db7c6)

I see that the librehardware binaries are all 32 bit. When I compile the sample code as 64 bit, everything works fine, when compiled as 32 bit, it doesn't show all sensors.

When digging through the code, found that x86 compiled app when run on ARM 64 machine detects vendor as Virtual CPU(and not as Intel or AMD)
![image](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/76487202/a110deb3-ad8d-4e92-b238-bea766afa731)

Same code compiled as x64 and run on ARM64,
![image](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/76487202/28eacd3b-2ed5-4754-b219-59b35eedb767)

**Comment by PhyxionNL** [comment]
This is unlikely to get fixed, see https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/1162
