### ISSUE TITLE
High temperature readings on Asus Prime B650 Plus

### ISSUE THREAD

**Issue by L0Lock** [LibreHardwareMonitor/LibreHardwareMonitor#1447]
I'm using [Rem0o/FanControl.Releases](https://github.com/Rem0o/FanControl.Releases) which uses LHM to know the hardware temperatures.

It detects 6 sensors off my Asus Prime B650 Plus motherboard, and two of which (number 3 and 6) have significantly high temperatures, often in the 80s ⁰C even at startup doing nothing. I though something was odd, so I ran [HWiNFO](https://www.hwinfo.com/) to compare (folded sections have no temperatures).:

![image](https://github.com/user-attachments/assets/fc3d29f1-dcb5-4eea-a1dc-2024091d7695)

I don't see any of the corresponding temperatures.

**Comment by Tellinq** [comment]
Temperatures 3-6 are typically auxiliary sensors and have little meaning. I’d just ignore them.

If you want them removed outright, I can add a data entry for your specific board getting all the necessary details, but I’d need more data such as the voltages, which fan index corresponds in UEFI (`CHA_FAN#`/`CPU_FAN) from LHM in comparison to HWiNFO.

**Comment by L0Lock** [comment]
My understanding of the subject falls pretty short. But here is a screenshot of the three apps, I hope this can help:

![image](https://github.com/user-attachments/assets/8c65ac29-db85-4bc6-88d1-a391b920b180)

**Comment by Tellinq** [comment]
Showing the default LHM sensors does help give some insight.

Since FanControl is basically using LHM as a backend, we won’t need that for this use case 

On HWiNFO64, can you enable voltages so we can see what is listed on the ASUS PRIME B650-PLUS sections? The other sections in HWiNFO can be collapsed

On LibreHardwareMonitor, can you go to View -> Show Hidden Sensors. I’m wanting to see what sensors are available.

Once that’s complete I’d like to see an updated side by side comparison as you were doing.

**Comment by Tellinq** [comment]
That gives me a good chunk and guess of what fans are which.

Here's what I've done:

I've made a new build that should identify your specific board. I've filled in what I'm confident in as-is, but the majority of this is just filling in as many potential indexes as possible, whether they exist or not.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/10819089566

I recommend using the net472 package.

I'll still want verification in the UEFI on which fan corresponds to which just to make sure, but I'm confident I got the layout right.

When you do have time to get into the UEFI, I also want to see what available temperature sensors are reported in the UEFI. I'm seeing that for the most part, the CPU, CPU Package, Chipset, VRM, and/or Motherboard should get reported, but that always differs from board to board.

I've attached a screenshot of what I'm looking for to see:
![image](https://github.com/user-attachments/assets/b225fed0-148b-4298-a340-488187f74872)

**Comment by Tellinq** [comment]
Wasn’t sure if you got my previous reply. Just needing a screenshot via the latest build so I can see what temperature sources are available and what I got right/wrong. Once that’s done I should be able to have your board added officially. See previous comment for the build.

**Comment by L0Lock** [comment]
Hi, sorry for the delay, I got drowned in daily work. 

Here are a few screenshots:

![240919192946](https://github.com/user-attachments/assets/e6785c1d-6d08-4aff-a0a2-c262ad684d2d)  
![240919193011](https://github.com/user-attachments/assets/ff62fd76-be4d-431d-9ce3-7327829cf315)  
![240919193024](https://github.com/user-attachments/assets/e3a90176-6dbf-43a3-bd32-9c51abcd6008)  
![240919193032](https://github.com/user-attachments/assets/6ab3df82-8688-4dbb-a033-9ea2e0606843)  

And a screenshot from the net472 you linked above:


![image](https://github.com/user-attachments/assets/8492a097-769b-48ff-a514-52230fae533f)


Hope i got it right. Thanks for your help :)

**Comment by Tellinq** [comment]
Perfect! Board entry should be merged soon. Once that’s done, FanControl should also update LHM shortly after
