### ISSUE TITLE
Run On Windows Startup Broken

### ISSUE THREAD

**Issue by JoeBroesele** [LibreHardwareMonitor/LibreHardwareMonitor#150]
Checking Options->"Run On Windows Startup" does not work anymore. After closing LibreHardwareMonitor, the option is reset to disabled and LibreHardwareMonitor won't automatically start on Windows startup.

**Comment by Phyxion** [comment]
The task for this was created but not checked correctly due to renaming of OHM to LHM. I'll address this.
