### ISSUE TITLE
Microsoft Defender For Endpoint Service Registration Alert

### ISSUE THREAD

**Issue by 3pichaxz0r** [LibreHardwareMonitor/LibreHardwareMonitor#1501]
We utilize microsoft defender for endpoint and when running librehardware monitor it triggers an alert stating a suspicious service is being registered. When checking the details it appears to be coming from WinRing0. I typically would call this a false positive but when looking into the details more I found the following information on processes created:
![image](https://github.com/user-attachments/assets/bf4bd09b-b061-43f6-bf3d-4da5571c0672)

Particularly I am concerned with "net1 start malware" which appears to be the service it is attempting to register and start

**Comment by PhyxionNL** [comment]
See WinRing0 issue.
