### ISSUE TITLE
Run On Windows Startup not working

### ISSUE THREAD

**Issue by JoeBroesele** [LibreHardwareMonitor/LibreHardwareMonitor#151]
Checking Options->"Run On Windows Startup" does not start LibreHardwareMonitor after reboot of Windows. When re-starting LibreHardwareMonitor manually, the option is still checked, but it seems to have no effect.

Technical background: The scheduled task that is being created by LibreHardwareMonitor gets a wrong execution folder. The parameter "Start in (optional):" of the task contains both the path plus the executable. E.g. it is "C:\Programs\LibreHardwareMonitor\LibreHardwareMonitor.exe" instead of "C:\Programs\LibreHardwareMonitor".

**Comment by Eno77** [comment]
I have the same issue, but on my build (AppVeyor 1.0.140) the option is unchecked again, every time I restart LHM.

**Comment by JoeBroesele** [comment]
The issue is fixed with the latest build (AppVeyor 1.0.151).
