### ISSUE TITLE
C# problem in vmware

### ISSUE THREAD

**Issue by tigros** [LibreHardwareMonitor/LibreHardwareMonitor#1514]
Hi,

In a C# program I have
```
computer.Open();
foreach (var hardware in computer.Hardware)
...
```

in a Windows 10 vm computer.Hardware is empty.

works fine on host computer.

**Comment by tigros** [comment]
ha! well i dunno something like cpu, cores, memory stuff like that, i can close this never mind then thanks!

**Comment by ergunodev** [comment]
Hi, i have ubuntu 24.04 runing on esxi host. I can not get gpu info. Nothing, no sensors also. Cpu, disk, network ok.
