### ISSUE TITLE
Display scaling not applied to column resize arrow..

### ISSUE THREAD

**Issue by freddellmeister** [LibreHardwareMonitor/LibreHardwareMonitor#154]
Makin resizing columns hard on 4k displays

**Comment by iNgeon** [comment]
With v0.9.4 even on 1440p it feels harder than it should be to resize the "value" "min" "max" "plot" colums.
Previous version this worked okay (think like 0.9.2 etc)

![2024-12-18_17-23-10-515_LibreHardwareMonitor_A0dhfaNZQU](https://github.com/user-attachments/assets/47548673-20b4-4d92-8cf1-5b3e06e6d918)

![2024-12-18_17-23-23-596_LibreHardwareMonitor_Cc3imKUa7T](https://github.com/user-attachments/assets/5d0cc20a-4294-4f02-b96c-a245ed2c5413)

![2024-12-18_17-23-37-903_LibreHardwareMonitor_VrDQEk6TZR](https://github.com/user-attachments/assets/17ba217f-23c3-4ef1-a442-b68f4d3444c2)

![2024-12-18_17-23-53-964_LibreHardwareMonitor_9EEtVwhY4U](https://github.com/user-attachments/assets/e785b91a-497f-4b5b-93ad-969b3cbe313e)
