### ISSUE TITLE
Mouse over Taskbar Icon still shows OpenHardwareMonitor

### ISSUE THREAD

**Issue by Eno77** [LibreHardwareMonitor/LibreHardwareMonitor#158]
Some String seems to be missed, when changing everything to "LHM" ;)

![LHM](https://user-images.githubusercontent.com/33687620/67214648-627cfd00-f420-11e9-9203-2d4d8088dd69.png)

**Comment by JoeBroesele** [comment]
This should be fixed with commit b62733a from 23 Oct 2019.
