### ISSUE TITLE
Axis labeling in plot window missing.

### ISSUE THREAD

**Issue by JoeBroesele** [LibreHardwareMonitor/LibreHardwareMonitor#161]
Both the x and y axis labeling is missing in the plot window. The autoscaling of the plot seems broken as well.

**Comment by Phyxion** [comment]
Is this issue now fixed with your PR?

**Comment by JoeBroesele** [comment]
Yes, the user can decide whether to display the axes labels or not (right-click -> Show Axes Labels).
In addition, there is a simple function to autoscale all y-axes. I find this especially handy when the axes labels are switched off, as one can easily get lost in 1e+/-xx scales by scrolling the mouse wheel. Right-click -> "Values Axes" -> "Autoscale All" will restore a usefull default zoom level on the y-axes.
