### ISSUE TITLE
Cant find CPU temperature in Intel Xeon E5-1620 v3

### ISSUE THREAD

**Issue by Nebukadnezzar13** [LibreHardwareMonitor/LibreHardwareMonitor#165]
Cant find CPU temperature in Intel Xeon E5-1620 v3
[OpenHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/3789024/OpenHardwareMonitor.Report.txt)

**Comment by Phyxion** [comment]
SB CPUs work for me, but it might've been fixed since opening this issue, so closing. If it's still not working please report back.
