### ISSUE TITLE
Images giving a HTTP 404 error on web page

### ISSUE THREAD

**Issue by xplosivmetal** [LibreHardwareMonitor/LibreHardwareMonitor#168]
Hi,

Obviously not a big issue but the image with the below URI is giving me a 404 error:

http://[ServerIp]:[ServerPort]/images_icon/internetspeed.png

This is the icon for network or storage throughput. On the app it shows a double diagonal arrow. Everything else loads fine.

![404 error](https://user-images.githubusercontent.com/9421058/68903122-02812a00-0732-11ea-9f53-16bcbf35f49f.png)

Thanks!

**Comment by MailYouLater** [comment]
Looks like this was fixed by f51f0378ec95d963be9535fef2bffe12833f7999 thanks to #193.
