### ISSUE TITLE
Some temperature offsets for AMD Zen(+) processors seem to be invalid

### ISSUE THREAD

**Issue by hirschmann** [LibreHardwareMonitor/LibreHardwareMonitor#176]
I had a look at the temperature offsets in [Amd17Cpu.cs](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Cpu/Amd17Cpu.cs#L214) and some of them seem to be wrong, compared to the values in [the Linux kernel](https://github.com/torvalds/linux/blob/master/drivers/hwmon/k10temp.c#L78) and this [offset table from AMD forums](https://community.amd.com/thread/231239#comment-2874504):

- 2600X: has no offset
- 2800X, 1910, 1920, 1950: afaik processors with those names don't exist

I'm not sure where the values in LHM come from and I haven't found a official document from AMD, but the sources I've found seem to be reliable.

**Comment by Phyxion** [comment]
Yeah, the current offsets don't make any sense. I'll modify it according to linux kernel, which seems to be the same as the table from AMD forums.
