### ISSUE TITLE
ryzen ccd temp implementation

### ISSUE THREAD

**Issue by LeagueRaINi** [LibreHardwareMonitor/LibreHardwareMonitor#183]
with the help of @KyodaiKen i added wip ccd temps, we tested it on a tr 3960x & r5 3600 and it seems to correspond to what hwinfo is showing (with slight differences cause the pooling rate is ofc not the same) would be nice if we could gather some more info regarding compatibility here 

![preview](https://i.imgur.com/kMDJ79l.png)

https://github.com/LeagueRaINi/LibreHardwareMonitor/blob/dev/LibreHardwareMonitorLib/Hardware/Cpu/Amd17Cpu.cs#L255

// also added ccd's max & average

**Comment by Phyxion** [comment]
That's nice, please submit a PR for this.
