### ISSUE TITLE
Gadget vanishes when using "show desktop" button.

### ISSUE THREAD

**Issue by uglitangeo** [LibreHardwareMonitor/LibreHardwareMonitor#190]
Every time I click on the lower right corner to show desktop the gadget vanishes. 
I'm using the same settings I had with OpenHardwareMonitor as it didn't exhibit this behavior, but no luck.

**Comment by tacal666** [comment]
hi, i already report this issue https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/182
