### ISSUE TITLE
GPU Package Power backwards for SLI

### ISSUE THREAD

**Issue by KiralyCraft** [LibreHardwareMonitor/LibreHardwareMonitor#196]
I am running two 1080 Ti's in SLI on an Asus Prime x570 Pro motherboard. It looks to me that the power indicators for the GPU's are backward. When only one GPU is active driving monitors (all of them are plugged into the first, top-most GPU), it has the fastest clock speed of the two and should use the most power. However, according to LHM, they are switched.

EDIT: The top (main slot) GPU is also the gottest since it can't really breathe that easily. 

![image](https://user-images.githubusercontent.com/10259742/72526696-ae004500-386f-11ea-9857-f85377b963d7.png)

**Comment by Phyxion** [comment]
Thanks for the report, I suspect this happens because the ids used by NvApi are not the same as NvidiaML, I'll submit a change for this soon.

**Comment by KiralyCraft** [comment]
Yep, downloaded the new build, works perfectly now
