### ISSUE TITLE
CPU Ryzen 5 3600 Temperatures Fluctuates sometimes more than 5 Celsius

### ISSUE THREAD

**Issue by Edris89** [LibreHardwareMonitor/LibreHardwareMonitor#199]
Hi there,

I am using this program but when comparing it to the ryzen master temperature it fluctuates sometimes more than 5 celsius.

Also Ryzen Master Shows CCD 0
But this program shows CCD1 Temperature?
Am I doing something wrong?

**Comment by Phyxion** [comment]
That's because RM is using a different monitoring interval than LHM, this is to be expected. If you check average temperature over a few minutes for example you'll notice that they're very close.
LHM starts counting CCDs at 1, similar to cores.
