### ISSUE TITLE
AMD RX 580- not showing GPU temp

### ISSUE THREAD

**Issue by Ale008** [LibreHardwareMonitor/LibreHardwareMonitor#204]
My video card temps does not show at all.

[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/4161433/LibreHardwareMonitor.Report.txt)

**Comment by Rem0o** [comment]
Seems to be related to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/186

**Comment by SharpOB** [comment]
Issue isn't present in 1.0.157. The problem was introduced in a build between that and 1.0.172.
![image](https://user-images.githubusercontent.com/24550634/74606476-84ce1100-50c8-11ea-9651-e37ab4c4816e.png)

**Comment by Phyxion** [comment]
This should be fixed now, closing.
