### ISSUE TITLE
Command line version of HW monitor

### ISSUE THREAD

**Issue by totalnooob** [LibreHardwareMonitor/LibreHardwareMonitor#205]
Hello is there a command line version of this software? I would need it to save log to txt file. Ive used different version of open hardware monitor with exe file OpenHardwareMonitorReport.exe but this show much higher cpu temperatures with threadripper cpus. Or is there a way to save txt logs via bat script?

**Comment by Phyxion** [comment]
No, there isn't, you can easily write it yourself though by referencing LibreHardwareMonitorLib.

**Comment by totalnooob** [comment]
Can you do it ?

**Comment by Phyxion** [comment]
You'll have to make it yourself, it's outside the scope of this.

**Comment by totalnooob** [comment]
Im pretty bad at programming... Do i just compile this? Where can I change to use the libre dll?
https://github.com/openhardwaremonitor/openhardwaremonitor/pull/1000

**Comment by totalnooob** [comment]
Ok nevermind found it
