### ISSUE TITLE
No separation line between stacked plots

### ISSUE THREAD

**Issue by tnodet** [LibreHardwareMonitor/LibreHardwareMonitor#208]
I noticed a minor GUI regression that appeared some revisions back.
The issue is that when "Stacked Axes" is checked and several x-axes (i.e. unit axes) are displayed in the plot panel, there is no separation (no black horizontal line) between the plots, where there used to be one.

The regression appeared in build 1.0.150 (commit [Migrate OxyPlot to NuGet version (#156)](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/bae89127b2d6c1813a9b8736a63a5c997541ff9a)).

Some screenshots will help clarify:

- Stacked axes in LibreHardawareMonitor 1.0.149:
![LibreHardwareMonitor-1.0.149](https://user-images.githubusercontent.com/11060057/75115325-9762c000-565d-11ea-93b3-d09dbc602e77.png)
- Stacked axes in LibreHardawareMonitor 1.0.173:
![LibreHardwareMonitor-1.0.173](https://user-images.githubusercontent.com/11060057/75115340-bcefc980-565d-11ea-8d48-fb6611f6799c.png)

In the seccond screenshot, notice how the green curve of the top plot (GPU Core clock) is cut under a certain value (where the middle plot starts), with no separation line.

**Comment by lordmortis** [comment]
I've got a partial fix to this in a branch i'm working on. It puts the lines in, but it might double them up - but i've noticed another problem with plotting where it's not auto-setting the size of the plot properly and i want to take a look at that before putting in the PR. https://github.com/lordmortis/LibreHardwareMonitor/tree/fixedPlotting

**Comment by tnodet** [comment]
Thank you very much for the fix, @lordmortis :)
Can I ask, is there a particular reason you gave the lines a thickness of 2?
I just find them to be a bit too thick next to the outer plot borders, which are 1px thick.
