### ISSUE TITLE
Support Asus Prime B350M-A

### ISSUE THREAD

**Issue by dokotr** [LibreHardwareMonitor/LibreHardwareMonitor#211]
Can be added support for Asus Prime B350M-A, Super I/O: ITE IT8655E, not detecting fans.

https://imgur.com/jUD3Nmt

**Comment by Phyxion** [comment]
Can you try the latest build (https://ci.appveyor.com/project/LibreHardwareMonitor/librehardwaremonitor)? IT8655E is included in there.

**Comment by dokotr** [comment]
Thank you, just tried latest build 1.0.176 and no change, not readings from cpu or chasis fun, voltage or temp from mobo.
https://imgur.com/BZ8CfbK

Is there anything can do to help you to resolve it? Consider not programmer...

**Comment by Phyxion** [comment]
Can you add the report here?

**Comment by dokotr** [comment]
Sure
https://webshare.cz/#/file/2hs3182Os5/b350m-a-log

**Comment by Phyxion** [comment]
Can you try the latest build? If it's still not working, can you also add the report of LHM?

**Comment by dokotr** [comment]
Tried 1.0.178, not working but there is a change, ID of Super I/O chip shown up. Screenshot and report from LHM attached.

report:
https://webshare.cz/#/group/zQEtcGulYw/
Screenshot:
https://imgur.com/Kj785Ya

**Comment by Phyxion** [comment]
Please try the latest build again.

**Comment by dokotr** [comment]
Tried 1.0.179, same as on previous build, just showing name of super io. Report from LHM attached.

https://en.webshare.cz/#/group/oYOUdEWpvv/

**Comment by dokotr** [comment]
Just tried latest build 1.0.190 and mobo sensor's are working ! Note sure whats gona change as I didn't find any description related to this issue in the change log.
