### ISSUE TITLE
Fan control on ITE IT8665E not working properly

### ISSUE THREAD

**Issue by nirvanaosc** [LibreHardwareMonitor/LibreHardwareMonitor#229]
I have an Asus Crosshair VI Hero with IT8665E Super IO.

I am testing with a Be Quiet! Silent Wings 3 PWM 1500RPM fan connected to the system fan headers on the motherboard.

If I select "Manual" on the appropriate fan controller, the fan stays at 300 RPM despite which % I select. When I select "Default" the fan runs at 600 RPM.

You can create fan curves on the BIOS to control the fan headers (but choices are quite limited). You can also select PWM and DC fan control on the motherboard.

I tested leaving everything by default on the motherboard with PWM control.

I also have some 3-pin fans I would also like to control on LibreHardwareMonitor if possible, with DC instead PWM.

I also tested with 3-pin fans and selecting any % in the fan controller has no effect, so I guess it changes the PWM signal only.

**Comment by javguit** [comment]
Changes to it87xx (and some it86xx) were made recently. Can you please update and test if works?

**Comment by nirvanaosc** [comment]
Same results.

**Comment by Rem0o** [comment]
Lookup over here... https://github.com/openhardwaremonitor/openhardwaremonitor/commit/7bf4f655d2c3ad9b660b6703c632b1d5694778ca

**Comment by Phyxion** [comment]
[LHM.zip](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/4573590/LHM.zip)

Can you give this a try?

**Comment by pfto** [comment]
My issues are fixed with it. Everything working as expected, thank you.
