### ISSUE TITLE
Fan control on IT8792E/8795E not working & on IT8688E not working properly

### ISSUE THREAD

**Issue by pfto** [LibreHardwareMonitor/LibreHardwareMonitor#235]
**Release:** 1.0.186
**Motherboard**: Gigabyte X570 Aorus Pro

*Problem with IT8688E:*

- Any value set for fan control within 0 to 50% spins fan up to around 65% RPM. 
- If set >50% the fan speed returns to current curve set in BIOS.

*Problem with IT8792E/8795E:*
- Any value set with fan control seems to be ignored and does not affect the fan speed.

Similar Issues: #229 #216

**Comment by Phyxion** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/229#issuecomment-623334538

**Comment by pfto** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/229#issuecomment-623531129

**Comment by rmattuschka** [comment]
The Size of the PWM Value in this register is only 7 bits [6:0]

You can try this in Row 258:	WriteByte(FAN_PWM_CTRL_EXT_REG[index], (byte)(value.Value >> 1));
instead of:      		WriteByte(FAN_PWM_CTRL_EXT_REG[index], value.Value);
                    
Maybe it works

**Comment by CSchuetz7** [comment]
@rmattuschka 

Doesn't help either, unfortunately.
