### ISSUE TITLE
Fans (RPM) not available via lib, SensorType.Control are showing up fine

### ISSUE THREAD

**Issue by uberhalit** [LibreHardwareMonitor/LibreHardwareMonitor#236]
I can not access any Fan sensors (RPM) through the LibreHardwareMonitorLib, the control-sensors (speed-percentage) are working fine though. I am accessing the sensors like: 

```cs
Computer computer = new Computer();
computer.IsControllerEnabled = true;
computer.IsMotherboardEnabled = true;
computer.Open();
List<ISensor> sensors = new List<ISensor>();
foreach (IHardware computerHardware in computer.Hardware)
{
    computerHardware.Update();
    foreach (ISensor sensor in computerHardware.Sensors)
    {
        sensor.Hardware.Update();
        sensors.Add(sensor);
    }
    foreach (IHardware sensorController in computerHardware.SubHardware)
    {
        foreach (ISensor sensor in sensorController.Sensors)
        {
            sensor.Hardware.Update();
            sensors.Add(sensor);
        }
    }
}
```
![grafik](https://user-images.githubusercontent.com/19159295/80490997-6e62f200-8962-11ea-80ce-a4325dc285be.png)

As you can see there are 6 `SensorType.Control` but no `SensorType.Fan`. This is how it looks like in the utility: 
![grafik](https://user-images.githubusercontent.com/19159295/80489692-820d5900-8960-11ea-93ed-e7e5a45ba992.png)

There are **7** sensors, both Control type and Fan type. Fan 2 and 5 are reporting 0 RPM though.

**Comment by riQQ** [comment]
Have you checked #207?

**Comment by uberhalit** [comment]
> 
> 
> Have you checked #207?

Yes, it's not the same issue. #207 didn't enumerate SubHardware, my problem is Fan sensors are not available at all.

**Comment by Phyxion** [comment]
You need to recursively update the hardware, and run as admin. Usually the fans are available only on the second update as they are activated after the first update.
