### ISSUE TITLE
Bogus CCD sensors dynamically added with incorrect values

### ISSUE THREAD

**Issue by aaronjwood** [LibreHardwareMonitor/LibreHardwareMonitor#237]
A picture is worth a thousand words :)
![Capture](https://user-images.githubusercontent.com/446283/80679765-6003fb80-8a72-11ea-9fea-696e2696ea02.PNG)

All I did was leave LHW open for some time as I was compiling some stuff and saw this behavior in order:

1. Max and average CCD temp values went off the charts
2. Bogus CCD sensors popped up shortly after with the same crazy values

**Comment by chitza** [comment]
Is that a Ryzen CPU? I remember seeing something like that too, but I can't reproduce it anymore.

**Comment by aaronjwood** [comment]
Yeah, sorry I should have specified that I'm running a 3950x on X570 (ASRock Taichi). I'm not sure how to reproduce it either, so far I've only seen it once in a fairly heavy-load situation. This was also with the latest release zip from a few hours ago too.

**Comment by Phyxion** [comment]
Thanks for the report, this should no longer occur. If you still see it, please let me know.
