### ISSUE TITLE
Support to IT8655E

### ISSUE THREAD

**Issue by TheTrueBumba** [LibreHardwareMonitor/LibreHardwareMonitor#246]
Worked until latest release and stopped now. I will try to check the code and find a solution. Can you check in your side?
Thanks in advance.
![libre](https://user-images.githubusercontent.com/1182236/81743429-ff17f280-9477-11ea-86b7-374a08cb3137.JPG)

**Comment by Phyxion** [comment]
Please take a look, I don't have any IT devices here to try it on.

**Comment by TheTrueBumba** [comment]
I checked the code. IT8655E enters in "generics sensors" code. I will try to identify how check fan sensors in my motherboard and paste the code here.
Open Hardware Monitor doesnt detect my sensor, BTW.

**Comment by Phyxion** [comment]
Weird, please let me know if you find the correct ID for it.

**Comment by TheTrueBumba** [comment]
I checked better. If I understood your code correctly, it return empty em fan sensors collection. Some paid solutions capture my ASUS Prime B450 correctly. I saw a library using WMI to capture the sensors. The library was developed by a third part developer? I can atach here the debug screen from my Visual Studio. Fan collection (The others sensors too) empty before choosing the motherboard manufacturer.
Very, very weird.
I am learning your code and I will install Visual Studio in another machine to compare the sensors detection using a older sensor and motherboard model.

**Comment by Phyxion** [comment]
You can check in LpcIO and IT87XX where things go wrong, I don't have a device with this sensor.

**Comment by TheTrueBumba** [comment]
Tnxs. I found the issue, now I need to know how to resolve or help you to resolve it.

In LPCIO.cs, line 174, you have the following code:
superIOs.Add(new IT87XX(chip, address, gpioAddress, version));

In IT87XX.cs, line 187, you have the condition below:
if (!valid || vendorId != ITE_VENDOR_ID)
  return;

In my motherboard, Asus PRIME B450M-GAMING/BR, vendorId has a value of 127 and ITE_VENDOR_ID has a value of 144, so the code step out the sensor chec. If I jump to line 191 and just hit "F5", everything runs fine since the code detects my IE correctly:

case Chip.IT8655E:
voltages = new float?[9];
temperatures = new float?[6];
fans = new float?[3];
break;

The question: Why vendorId and ITE_VENDOR_ID has different values? A not reconized motherboard? A issue? You guide me I can download the latest version, make the corretions and make a push.

I will keep studying here. Tnxs for the advice.

**Comment by TheTrueBumba** [comment]
Well, working here, but I dont know the reason since I am not a specialist in hardware sensors.
But changing the const ITE_VENDOR_ID to 0x7F worked like a charm.
private const byte ITE_VENDOR_ID = 0x7F; (Line 40 in IT87XX.cs)
Are there any sensor database so I can check the correct vendor ID?

**Comment by TheTrueBumba** [comment]
![image](https://user-images.githubusercontent.com/1182236/83324959-02182e80-a23f-11ea-94fe-23c587befe65.png)

**Comment by Phyxion** [comment]
Thanks for checking, I've added the other vendor id as well.

**Comment by oxirt** [comment]
Please note that the fan readings are incorrect. See ticket 277.
