### ISSUE TITLE
Compile Error with pull request #23

### ISSUE THREAD

**Issue by d-ahrens** [LibreHardwareMonitor/LibreHardwareMonitor#25]
@Phyxion created a build error with his commit:
Merge branch 'pr/23'
#23 

Two lines in the switch-case statement (around line 190) disappered which were present in @dougvj original commit.

original: (dougvj)

> 186 +              case 0xAE: // Intel Core i5, i7 8xxxx (14nm++)
> 187 +                microarchitecture = Microarchitecture.CoffeeLake;
> 188 +                tjMax = GetTjMaxFromMSR();
> 189 +                break;

pull request #23 : (Phyxion)

> 190 +              case 0xAE: // Intel Core i5, i7 8xxxx (14nm++)
> 191 +                microarchitecture = Microarchitecture.CoffeeLake;

**Comment by Phyxion** [comment]
Yes, sorry, it got messed up with rebasing.
