### ISSUE TITLE
ITE IT8665E Reads voltages wrongly

### ISSUE THREAD

**Issue by DjordjeMandic** [LibreHardwareMonitor/LibreHardwareMonitor#252]
Compared to OpenHardwareMonitor there is big difference in VBat voltage readout and there is also few voltages missing.
![image](https://user-images.githubusercontent.com/6750655/82515998-faa7a580-9b19-11ea-8d06-6f2e64ce3174.png)
Other voltages seem fine, little difference. Changing resistor divider ratio to 10 10 from 0 1 make readings a little bit okay but still not the same. 

Question: Are you doing development for this fork independently of ohm or youre following its progress and importing the changes from official ohm?

**Comment by Phyxion** [comment]
Can you check the latest build again?

**Comment by Phyxion** [comment]
@DjordjeMandic Please give this a try:
[Release.zip](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/4725908/Release.zip)
Write these files over the latest build on main page.

**Comment by DjordjeMandic** [comment]
![image](https://user-images.githubusercontent.com/6750655/83817865-26a05a80-a6c6-11ea-9b95-709fa2caec67.png)
Yeah its better now but i still dont get it why is LHM measuring little bit less compared to OHM, look at maximum values. VBat is still off

**Comment by Phyxion** [comment]
That's because OHM has a different voltage gain for it, [IT8665E ](https://github.com/a1wong/it87/blob/master/it87.c#L718)uses 0.0109 gain and not 0.011.
