### ISSUE TITLE
Can't control NVIDIA RTX GPU Fan

### ISSUE THREAD

**Issue by Nama** [LibreHardwareMonitor/LibreHardwareMonitor#274]
LHM is able to control all control sensors I have except for the GPU.

If I list the functions in sensor.Control, SetSoftware() etc. are all missing.
```
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

My graphics card is a MSI Armour 2070 RTX 8G. MSI Afterburner can control it. The sensor is read correctly.

**Comment by PhyxionNL** [comment]
This should be fixed by #479.
