### ISSUE TITLE
ASUS PRIME B350-PLUS (ITE IT8655E/GX)

### ISSUE THREAD

**Issue by Gae-IT** [LibreHardwareMonitor/LibreHardwareMonitor#277]
The cpu fan speed is not correct, although ITE IT8655E should be supported

could someone fix it?

thanks

**Comment by osmiyaki** [comment]
is there a way to help this could be supported?

**Comment by Phyxion** [comment]
We'd need someone that has this sensor and knows how to code, I don't have any device with this sensor.

**Comment by OlympicLarry** [comment]
@PhyxionNL I have this sensor (Asus Prime 450M-A) and I am a .net programmer (web/sql), but I have no experience with this type of programming. Care to walk me through it?

**Comment by PhyxionNL** [comment]
One useful resource is this (as it already implements this sensor for Linux):
https://github.com/a1wong/it87/blob/master/it87.c
There you can see the features it uses:
`FEAT_NEWER_AUTOPWM | FEAT_16BIT_FANS
		  | FEAT_AVCC3 | FEAT_NEW_TEMPMAP | FEAT_SCALING
		  | FEAT_10_9MV_ADC | FEAT_IN7_INTERNAL | FEAT_BANK_SEL
		  | FEAT_SIX_TEMP | FEAT_MMIO`

You will need to look into https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/IT87XX.cs and see what's wrong. Just looking at the it87 code the fan registers (FAN_TACHOMETER_EXT_REG) seem to be different for IT8655E, but it might also require some other changes. The easiest way is to check the FEAT_ stuff in it87 and compare with IT87XX.cs and go from there. There's not much documentation on these sensors so it's often trial and error.

**Comment by oxirt** [comment]
I'm facing the same issue on ASUS EX-A320M-GAMING motherboard, fan readings are incorrect.

I was able to fix fan readings. In file `IT87XX.cs` line 72-79 for `_hasExtReg` check, I added `chip == Chip.IT8655E`. However, I'm not able to fix PWM controls. Any suggestions?

**Comment by oxirt** [comment]
Nevermind, even the PWM control is working now. Will raise a PR shortly.

**Comment by Gae-IT** [comment]
> 
> 
> Nevermind, even the PWM control is working now. Will raise a PR shortly.
> 
> Edit: fixed with #327 @Gae-IT I have tested on my board. Can you also test this please?

Hello oxirt,
thanks for your contribution, but for me don'r report correct values
![immagine](https://user-images.githubusercontent.com/64748300/98515256-168b3900-226b-11eb-9ed7-aa87df54a521.png)
on the left the results of Asus AI Suite 3

**Comment by Gae-IT** [comment]
differences in https://github.com/a1wong/it87/blob/master/it87.c at line 305-306
static const u8 IT87_REG_PWM[] =	{ 0x15, 0x16, 0x17, 0x7f, 0xa7, 0xaf };
static const u8 IT87_REG_PWM_8665[] =	{ 0x15, 0x16, 0x17, 0x1e, 0x1f, 0x92 };

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/IT87XX.cs at line 69-70
                ? new byte[] { 0x15, 0x16, 0x17, 0x1e, 0x1f }
                : new byte[] { 0x15, 0x16, 0x17, 0x7f, 0xa7 };

at line 72:
hasExtReg should be true also for IT8655E ?

it's not easy to comapre both file, it's written in a completely different way (at least for me ;-) )

**Comment by oxirt** [comment]
> 
> 
> > Nevermind, even the PWM control is working now. Will raise a PR shortly.
> > Edit: fixed with #327 @Gae-IT I have tested on my board. Can you also test this please?
> 
> Hello oxirt,
> thanks for your contribution, but for me don'r report correct values
> ![immagine](https://user-images.githubusercontent.com/64748300/98515256-168b3900-226b-11eb-9ed7-aa87df54a521.png)
> on the left the results of Asus AI Suite 3

@Gae-IT My PR is not merged yet, hence you need to pull it, compile it and then test. I hope you're doing the same.

**Comment by Gae-IT** [comment]
ops, sorry, I can't compile, I just downloaded latest binaries. I'll wait for the merge, fool sorry :(

**Comment by oxirt** [comment]
> it's not easy to comapre both file, it's written in a completely different way (at least for me ;-) )

True, but the overall functionality is same. The sensor has:

- Few *default report registers* to read fan values
- Few *extended report registers* to read fan values
- Few *default control registers* to set fan values
- Few *extended control registers* to read fan values

What is difference between default and extended report/control registers, I'm not sure. My approach was, if defaults are not working, use extended.

**Comment by oxirt** [comment]
@Gae-IT if you want to dig deeper, https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config has a very good writeup.

**Comment by oxirt** [comment]
> I'll wait for the merge

@Gae-IT mods will not merge until you confirm it working :-D @PhyxionNL is there a way around it? Any intrim build that Gae can download?

**Comment by Gae-IT** [comment]
I've downloaded binaries from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/355620077
and also from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/327/checks?check_run_id=1370547843
but same results, not works for me
![immagine](https://user-images.githubusercontent.com/64748300/98670525-1b2b1c80-2353-11eb-87d8-a407455fd5bc.png)

**Comment by oxirt** [comment]
![image](https://user-images.githubusercontent.com/40735859/98686778-f94f8b00-238e-11eb-9243-1cb92a4a4998.png)

@Gae-IT can you tell me your AMD driver version?

**Comment by Gae-IT** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/40735859/98686778-f94f8b00-238e-11eb-9243-1cb92a4a4998.png)
> 
> @Gae-IT can you tell me your AMD driver version?

@oxirt my AMD driver version is the same as you 2.10.13.408
![immagine](https://user-images.githubusercontent.com/64748300/98696559-3d816200-2374-11eb-9124-fd44e0b666a5.png)

**Comment by PhyxionNL** [comment]
I don't think the driver version matters here. @oxirt Are your fan readings correct with what motherboard reports?

**Comment by ackstorm23** [comment]
I have this same problem on my TUF-B450-PLUS-GAMING.

It's IT8655E.

The fan speeds read correctly in another program, Argus Monitor.  However in LibreHardwareMonitor they are way off.

**Comment by ackstorm23** [comment]
I used the same links as Gae-IT to test but the fan speeds still report incorrectly.

**Comment by ackstorm23** [comment]
This still isn't fixed 2 years later :(

**Comment by PhyxionNL** [comment]
> This still isn't fixed 2 years later :(

You're more than welcome to work on it :)

**Comment by AyamiAlince** [comment]
> 

3 Years not fixed

**Comment by MadGoatHaz** [comment]
Asus TUF B450m-pro S w' ITE - IT8655e

Issue persists
