### ISSUE TITLE
Please add support for Winbond/Nuvoton NCT6687D 

### ISSUE THREAD

**Issue by PaulPiatek** [LibreHardwareMonitor/LibreHardwareMonitor#278]
This chip is used on the MSI MPG Z490 GAMING CARBON WIFI (MS-7C73), but unfortunately not supported by LibreHardwareMonitor yet.

**Comment by Rem0o** [comment]
NCT6687D gives the following log:

**LpcIO

Chip ID: Unknown Winbond / Nuvoton / Fintek with ID 0xD592 at 0x4E/0x4F**

So id = 0xD5 and revision is 0x92

**Comment by Phyxion** [comment]
There doesn't seem to be much information about this chip, it might be possible to get some basic support for it by adding that identifier / revision, but ideally someone with this chip should add/test it.

**Comment by fraybentos** [comment]
If someone can add the NCT6687D identifier and revision and send me the compiled build, I'd be happy to test it and report back. It looks like this chip is used in all the Z490 MSI boards.

**Comment by fraybentos** [comment]
This looks request looks like it can be a closed: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/288
