### ISSUE TITLE
Version not updated in About window

### ISSUE THREAD

**Issue by osmiyaki** [LibreHardwareMonitor/LibreHardwareMonitor#279]
![image](https://user-images.githubusercontent.com/10911107/87498829-60964200-c61e-11ea-9a4c-dcae42e76707.png)

I download the lastest relase from the appveyor site and the About windows shows another version which should be 1.0.204

**Comment by Phyxion** [comment]
This is because the AppVeyor build version is different from application. I agree this is confusing. but AppVeyor can only update new csproj format as far as I know and the UI project is still using the old csproj format.

**Comment by PhyxionNL** [comment]
This is fixed some time ago.
