### ISSUE TITLE
(Noob Question) where does the example code go inside Visual Studio?

### ISSUE THREAD

**Issue by Just-Ch33s3** [LibreHardwareMonitor/LibreHardwareMonitor#281]
Hi again, I've opened up a new Visual Studio Project and would like to create a Console App (Net Framework) to read out values and learn to tweak it... i hope that was correct so far...
As described, I've added both LHMLib + HidSharp to the project, in which "field" does the example code featured on the start page need to go?
![vst2019](https://user-images.githubusercontent.com/49145093/87849224-26ab9100-c8e7-11ea-9f50-be972e0aad53.png)
( a simple arrow would probably work wonders ! :) )
Any help is appreciated!
Thanks in advance for your help! :)

**Comment by Phyxion** [comment]
You can paste the contents of the example code below "class Program {". Then inside Main method you need to add Monitor(); But it would be best to start with a guide like this:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/hello-world-your-first-program?tabs=windows

**Comment by Phyxion** [comment]
Just closing as it's not an issue with the program, feel free to continue here.

**Comment by cednieb** [comment]
check this thread : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/207

**Comment by Just-Ch33s3** [comment]
> You can paste the contents of the example code below "class Program {". Then inside Main method you need to add Monitor(); But it would be best to start with a guide like this:
> https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/hello-world-your-first-program?tabs=windows

Sorry for the late reply, I'll give it a shot thank you!

**Comment by Just-Ch33s3** [comment]
![nettest](https://user-images.githubusercontent.com/49145093/90411172-a3c75300-e0ab-11ea-89c3-6e19d25d47e2.png)
Unfortunately no luck on this approach, your'e totally right about the getting started page regarding .Net
I'd just love to play some trial and error with this code to test some functions - would you be so kind and check if I did anything wrong here ?

**Comment by lecciovich** [comment]
@Just-Ch33s3 I was in same condition as noob C# programmer.
I started from an HelloWorld and retrieved this

`
// LHM Sample Code program
using System;
using LibreHardwareMonitor;
using LibreHardwareMonitor.Hardware;
using HidLibrary;

namespace SampleCode//HelloWorld
{
    class SampleCode
    {
        public class UpdateVisitor : IVisitor
        {
            public void VisitComputer(IComputer computer)
            {
                computer.Traverse(this);
            }
            public void VisitHardware(IHardware hardware)
            {
                hardware.Update();
                foreach (IHardware subHardware in hardware.SubHardware) subHardware.Accept(this);
            }
            public void VisitSensor(ISensor sensor) { }
            public void VisitParameter(IParameter parameter) { }
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            UpdateVisitor visitor= new UpdateVisitor();

            Computer computer = new Computer
            {
                IsCpuEnabled = true,
                IsGpuEnabled = true,
                IsMemoryEnabled = true,
                IsMotherboardEnabled = true,
                IsControllerEnabled = true,
                IsNetworkEnabled = true,
                IsStorageEnabled = true
            };

            computer.Open();
            computer.Accept(new UpdateVisitor());

            foreach (IHardware hardware in computer.Hardware)
            {
                Console.WriteLine("Hardware: {0}", hardware.Name);

                foreach (IHardware subhardware in hardware.SubHardware)
                {
                    Console.WriteLine("\tSubhardware: {0}", subhardware.Name);

                    foreach (ISensor sensor in subhardware.Sensors)
                    {
                        Console.WriteLine("\t\tSensor: {0}, value: {1}", sensor.Name, sensor.Value);
                    }
                }

                foreach (ISensor sensor in hardware.Sensors)
                {
                    Console.WriteLine("\tSensor: {0}, value: {1}", sensor.Name, sensor.Value);
                }
            }


            computer.Close();

        }


    }
}

`
Hope it can be useful.
