### ISSUE TITLE
ITE IT879XE control support

### ISSUE THREAD

**Issue by AdriaanDeVos** [LibreHardwareMonitor/LibreHardwareMonitor#283]
**Problem description**
As a user I would like to be able to control the fans of an IT879XE. The current application provides the actual values of this device, but the fan control functionality does not seem to work.

**Describe the solution you'd like**
Expand current read-only support of IT879XE to support full fan control.

**Describe alternatives you've considered**
Check this project for information about IT879XE support. https://github.com/openhardwaremonitor/openhardwaremonitor/commit/7bf4f655d2c3ad9b660b6703c632b1d5694778ca

**Additional Context**
Hardware used:
Gigabyte X570 Aorus Pro Rev 1.0
ITE IT8688E for 6 temperature readings and 5 fans, ITE IT879XE for 3 more temperatures and 3 more fans

**Comment by PhyxionNL** [comment]
Fan control is broken in OHM as well, someone with this chip needs to try and fix this and submit a PR for it.

**Comment by DarkIrata** [comment]
https://github.com/openhardwaremonitor/openhardwaremonitor/issues/1287 
An old open issue to that problem. Just to link it.

**Comment by dephcon** [comment]
also have this issue, however my x570 Master rev1.0 has a IT8975E as the secondary fan controller with the primary IT8688E.

**Comment by CreeT6** [comment]
i have x570 aorus pro, same issue

**Comment by virusmoere** [comment]
Is there  anything I can do to support development in this case? I could supply remote access to the sensor if needed for some testing.

**Comment by ajhix36** [comment]
Any work on this? I have the same issue :(

**Comment by Koli0842** [comment]
I also encountered this issue. RPMs are read just fine, but control does not seem to do anything (from FanControl). How does one figure this out without breaking things? If the Linux WMI support gives a good reference, I'm willing to test this on my X570 Pro, but would rather not drill into it headfirst.

**Comment by NormanPCN** [comment]
I am in this same boat. Gigabyte z390 Aorus Master MB.

it879xe fan headers are reading speed but no control (FanControl software).  No control or the MB and FanControl are fighting over control. Force applying in FanControl is no change.

I can likely move my fans to other fan headers. it8688e controller. I have only one fan on the it879xe right now.

**Comment by PhyxionNL** [comment]
Continue at #251.
