### ISSUE TITLE
Port to NET Core 3.1 via Microsoft.Windows.Compatibility 3.1.0

### ISSUE THREAD

**Issue by perestoronin** [LibreHardwareMonitor/LibreHardwareMonitor#286]
Please port to NET Core 3.1  via Microsoft.Windows.Compatibility 3.1.0

**Comment by PhyxionNL** [comment]
Sadly this doesn't work magically, there are quite a lot of elements removed for WinForms in .NET Core. If you'd like the UI ported to .NET Core, please submit a PR.

**Comment by ManuelKugelmann** [comment]
An older version of the lib is ported: https://github.com/Epsil0neR/openhardwaremonitor-core

**Comment by PhyxionNL** [comment]
Library already runs .NET Standard, which is compatible with .NET Core. The UI is a whole different part.
