### ISSUE TITLE
ASRock x570 Taichi/NTC6796D-R Temp Sensors strange behaviour 

### ISSUE THREAD

**Issue by NIoSaT** [LibreHardwareMonitor/LibreHardwareMonitor#290]
When I start the software I can only see Temperature 1, 3, 5, 6 and they don't seem to correspond to any Temps I can see in the A-Tuning utility(CPU+MB+Chipset/SB) and remain static.
HWInfo64 shows MB+CPU+SB+AuxTIn2-4+CPU(PECI) but only the first 3 seem to give meaningful measurements.

Most of the time it stays like this, but sometimes the missing sensors appear after minimizing and reopening the program.
I was not able to figure how to reproduce this consistently.

**Comment by seiphr** [comment]
I can confirm the issue on my AsRock x570 Taichi. Issue still present with latest 4.00 BIOS.
