### ISSUE TITLE
IT8728F control

### ISSUE THREAD

**Issue by XNtricity** [LibreHardwareMonitor/LibreHardwareMonitor#294]
**Problem description**
Systems with the IT8728F controller operate in read-only mode. The application can see the controller and its values, but fans connected cannot be controlled.

**Describe the solution you'd like**
Update software to allow user control of fans connected to the IT8728F controller.

**Describe alternatives you've considered**
SpeedFan supports this controller, however SpeedFan is old and no longer supported. I would like to migrate to a newer and supported application.

**Additional Context**
Hardware used:
Gigabyte Z87X-UD3H-CF
Motherboard has 6 fan headers: CPU_FAN, CPU_OPT, SYS_FAN1/2/3, and SYS-FAN4 is 3-pin only.

**Comment by DiegoJp** [comment]
Second this, my motherboard (Z77X-UD3H) also has ITE IT8728F.
Programs using this library can only show readings but no controlling.
SpeedFan and several other programs/libraries report 5 fan speed and 3 controls.
SpeedFan can control all of them.

**Comment by axcester** [comment]
Bump. My Gigabyte Z87X-UD4H also has this controller

**Comment by LAzinheira** [comment]
Same issue with GA-78LMT-USB3 (rev5.0) using the same controller.
Speedfan allows control of fan speed.
