### ISSUE TITLE
Qeustions about sensor and control on Crosshair VII Hero

### ISSUE THREAD

**Issue by dennis97519** [LibreHardwareMonitor/LibreHardwareMonitor#299]
Is it possible to show and control W_PUMP+? Not sure if the header is connected to IT8665E. Currently the fans 1-5 and control 1-5 maps to CPU fan, chassis fan 1-3, and HAMP fan.

The motherboard also has 2 CPU fan headers that have a common PWM control signal, but the application only shows one reading.

Also, is there an option to select PWM/DC output within IT8665E, or is this functionality provided by an external chip?

Are there plans to add sensor data from ASUS's WMI interface?

**Comment by PhyxionNL** [comment]
See https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/282, closing this for that.
