### ISSUE TITLE
Gigabyte Z390 M GAMING-CF (ITE IT8688E)

### ISSUE THREAD

**Issue by Wighty05** [LibreHardwareMonitor/LibreHardwareMonitor#301]
Missing Fan Controls in "FanControl.Releases-49" has GPU  but not MB

![ScreenShot](https://user-images.githubusercontent.com/71534792/93656641-c2e23900-f9f9-11ea-8170-78ce3b48182f.PNG)

[OpenHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/5248950/OpenHardwareMonitor.Report.txt)

**Comment by djbiti1** [comment]
I am having the same issue.

**Comment by Wighty05** [comment]
Ended up just using “Argus Monitor”
https://www.argusmonitor.com/downloads/ArgusMonitor_Setup.exe

**Comment by Wighty05** [comment]
> I am having the same issue.
