### ISSUE TITLE
Support AMD family 19h processors (Zen 3)

### ISSUE THREAD

**Issue by DevTechProfile** [LibreHardwareMonitor/LibreHardwareMonitor#310]
Hi, I'm a dev from the CapFrameX team. We have a similar hardware lib. Any plans to support Zen 3? 

The only source I have is a Linux patch: https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=2835d860d3fcc3e4829e96987544e811d35dee48

**Comment by PhyxionNL** [comment]
Sure, but let's wait until they're released so it can be tested.

**Comment by DevTechProfile** [comment]
We have implemented an experimental Zen 3 support: https://github.com/CXWorld/CapFrameX/commit/9b55c917d59240e6278b2e7437c2500fb74559f9

Patrick Schur checked the constants in the latest AGESA supporting Zen 3.

**Comment by PhyxionNL** [comment]
Nice work, please submit a PR, I'll gladly review it. Some of your other changes (e.g. to GPUs) are welcome too.

**Comment by luctowers** [comment]
Hi, I need this for a project I'm working on. I have a ryzen 7 5800x to test. I can test any changes put up. Or I can try my hand at adapting @DevTechProfile's changes myself if that's ok.

**Comment by PhyxionNL** [comment]
> Hi, I need this for a project I'm working on. I have a ryzen 7 5800x to test. I can test any changes put up. Or I can try my hand at adapting @DevTechProfile's changes myself if that's ok.

Yeah, sure, either should be fine, thanks 😁

**Comment by cwbr** [comment]
I could also provide testing on a 5900x (2 CCDs).

**Comment by luctowers** [comment]
> I could also provide testing on a 5900x (2 CCDs).

Sweet, tomorrow is a stat holiday in Canada. So, I'll try and hack a build together.

**Comment by luctowers** [comment]
Hmm, I may be in over my head. I got tCtl, tDie, core voltage and soc voltage working only because they were extermely similar Zen 2.  But, per-core clocks and VID have defeated me so far will keep digging.

**Comment by PhyxionNL** [comment]
Have you checked this: https://github.com/CXWorld/CapFrameX/commit/9b55c917d59240e6278b2e7437c2500fb74559f9
?

**Comment by DevTechProfile** [comment]
Per-core clocks work but we haven't VID yet.
