### ISSUE TITLE
Bug: Enumeration misses zero RPM fans

### ISSUE THREAD

**Issue by Korkman** [LibreHardwareMonitor/LibreHardwareMonitor#313]
Asus X99-E Mainboard with Nuvoton NCT6791D: The RPM readout of my three installed fans stops updating on the last non-zero readout when setting the fans to zero RPM. The effect being that those fans never get to display zero RPM.

**Comment by Korkman** [comment]
When set to zero RPM, the fans disappear from the list after restarting LHM. Showing "hidden sensors" does not show them either. Starting them again, producing non-zero RPM, makes them appear again in the running LHM instance.

**Comment by Korkman** [comment]
So in some way it does know the number of the fan but skips those reporting zero RPM for some reason:
![image](https://user-images.githubusercontent.com/3186931/96363837-f1f1e480-1136-11eb-9888-e4ba8edb6d38.png)

This must be filtered somewhere, but I don't see it in the code yet. Other software reports all six fans.

**Comment by PhyxionNL** [comment]
Thanks, it's merged.
