### ISSUE TITLE
Provide Binaries without the need to be logged in

### ISSUE THREAD

**Issue by Eno77** [LibreHardwareMonitor/LibreHardwareMonitor#316]
Is it possible to provide the binaries too, if the user is not logged in? Unfortunately the Link appears only, if a user is logged in.
If not, I suggest the "Releases / Tags" should contain the binaries too, beside the Source code packages.

**Comment by PhyxionNL** [comment]
Didn't know this required an account, I'll see if this can be automated, for now I've manually uploaded 0.8.5.

**Comment by RaydenX93** [comment]
An example of a repository that automatically generates a rolling release: https://github.com/stenzek/duckstation
