### ISSUE TITLE
Confusing version numbers

### ISSUE THREAD

**Issue by tjader0** [LibreHardwareMonitor/LibreHardwareMonitor#321]
I am confused by LibreHardwareMonitor's version numbers.

In github there's only one release at [v0.8.5](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.8.5).

The Help > About screen also says 0.8.5:
![image](https://user-images.githubusercontent.com/81907/97380533-0441f000-18a6-11eb-8df9-ac3a8da856d0.png)

However both [AppVeyor](https://ci.appveyor.com/project/LibreHardwareMonitor/librehardwaremonitor/history) and [Chocolatey](https://chocolatey.org/packages/libre-hardware-monitor) say the current version is 1.0.223.

**Comment by PhyxionNL** [comment]
AppVeyor is no longer used and Chocolately is an unofficial package, the only real source is GitHub. 0.8.5 is the current & latest version.
