### ISSUE TITLE
CPU sensors are reading from wrong cores due to CPU affinity issue

### ISSUE THREAD

**Issue by luctowers** [LibreHardwareMonitor/LibreHardwareMonitor#330]
Amd Zen relies on the thread executing on the respective core in order to get per-core sensor data. This does not seem to be working at the moment.

For example, in this screenshot a multitude of cores are shown at 4850MHz when in reality only one of them is.

![5800x frequency bug](https://camo.githubusercontent.com/746e426c6c508a27ff5fbeea373e7d888a917bdcc27dd4b77262d317b48f5d3b/68747470733a2f2f692e696d6775722e636f6d2f54724174594f462e706e67)

**Comment by luctowers** [comment]
Byproduct of #328

**Comment by PhyxionNL** [comment]
Can you tackle this @luctowers? I do not see this issue on my CPU.

**Comment by luctowers** [comment]
> Can you tackle this @luctowers? I do not see this issue on my CPU.

Will look into it this weekend, maybe it's something screwy with my environment.

**Comment by PhyxionNL** [comment]
I think this might be fixed in latest build, can you check it @luctowers.
