### ISSUE TITLE
NVIDIA NVML Driver

### ISSUE THREAD

**Issue by sebastian-dev** [LibreHardwareMonitor/LibreHardwareMonitor#344]
The new NVIDIA driver 460.79 has no nvml.dll in the NVSMI folder.
The access is changed to nvml_loader.dll.

Currently it is not possible to read out the power consumption.

Reference:
https://github.com/openhardwaremonitor/openhardwaremonitor/issues/1376

Possible solution:
https://github.com/nicehash/NiceHashMiner/commit/dc5971a04d447f89b5b8b7acc65c7cb3d0c00735

**Comment by aaronjwood** [comment]
Would just like to add that this breaks reading throughput as well.

**Comment by MerlinStWahgwaan** [comment]
Working HOTFIX from Nvidia....
Must be installed manually, but I can fonfirm, it works!

https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/421696/announcing-geforce-hotfix-driver-46097-released-12/
