### ISSUE TITLE
Crashes Possibly Related to LHM

### ISSUE THREAD

**Issue by CZonin** [LibreHardwareMonitor/LibreHardwareMonitor#345]
Myself and a few other users of [SidebarDiagnostics](https://github.com/ArcadeRenegade/SidebarDiagnostics), which uses LHM, have been experiencing a number of crashes for awhile. The developer suggested opening an issue here to see if anything can be done on your end. I've attached screenshots of the errors. Let me know if there's any other info I can provide that would be helpful.

If it helps, I'm using the latest version of Windows 10 (20H2 at time of posting) but the same issue has been present in previous versions.

![101642889-6f491f80-3a2b-11eb-9819-46f0be2e4dbe](https://user-images.githubusercontent.com/67965669/102386779-8e9cfb00-3f9d-11eb-85f7-d48e675c610b.png)
![95328418-89238600-0873-11eb-90fc-643a8d2bb1f5](https://user-images.githubusercontent.com/67965669/102386782-8e9cfb00-3f9d-11eb-98bc-71325f0da8d6.png)
![95328420-89238600-0873-11eb-9129-479e8d86d143](https://user-images.githubusercontent.com/67965669/102386784-8f359180-3f9d-11eb-8737-252e4d53d040.png)

**Comment by PhyxionNL** [comment]
The last is related to SidebarDiagnostics looking at the exception. The KrakenX3 issue might've been fixed by #355.
