### ISSUE TITLE
Binaries download 404

### ISSUE THREAD

**Issue by fabiensanglard** [LibreHardwareMonitor/LibreHardwareMonitor#348]
I am trying to download a release on this page:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions

However all Binaries are 404ing.

**Comment by riQQ** [comment]
You need to be logged in to download the artifacts.

**Comment by PhyxionNL** [comment]
> You need to be logged in to download the artifacts.

Exactly, this is not possible to change as far as I know. You can download it from the releases here though:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases
