### ISSUE TITLE
Bad firmware version scrape in KrakenX3.cs?

### ISSUE THREAD

**Issue by konistehrad** [LibreHardwareMonitor/LibreHardwareMonitor#355]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/1506006f4ec1e64096307554a63a57106cbb53c7/LibreHardwareMonitorLib/Hardware/Controller/Nzxt/KrakenX3.cs#L55

I believe the correct representation of this line would be `FirmwareVersion = $"{_rawData[0x11]}.{_rawData[0x12]}.{_rawData[0x13]}";`  I'm working on adding support for Nzxt's Smart Device V2, and it shares an initialization routine with the KrakenX3. I'd open a PR for this, but I don't have hardware to ensure that this is correct. ([liquidctl seems to indicate](https://github.com/liquidctl/liquidctl/blob/59f2b7c1db9a676480894209b95263340ed26365/liquidctl/driver/kraken3.py#L178) that this is correct, however.)

**Comment by CZonin** [comment]
I think this could be related to an issue I opened awhile ago https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/345

**Comment by PhyxionNL** [comment]
Is likely x12 indeed, reading x11 twice doesn't make sense.
