### ISSUE TITLE
DIMM temperature probe

### ISSUE THREAD

**Issue by Cubox** [LibreHardwareMonitor/LibreHardwareMonitor#369]
Hi,

HwInfo can read my DIMM temperature (from the DIMM temperature sensors, not all sticks have one) 
![image](https://user-images.githubusercontent.com/479129/106014892-37229c80-60be-11eb-8d58-3b267c906135.png)

It'd be great to have this with the lib
I tried with the included .exe and DIMM is not shown
I'm happy to help in any ways to get the information needed for getting DIMM temperature implemented

**Comment by Eno77** [comment]
I think you may close this one, since some effort is already going into this.

See:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/395

**Comment by PhyxionNL** [comment]
Closing as duplicate.
