### ISSUE TITLE
Network duplicates

### ISSUE THREAD

**Issue by sinancetinkaya** [LibreHardwareMonitor/LibreHardwareMonitor#371]
Every time my pc (windows 10 x64) wakes up from hybrid sleep, network connections are getting duplicated as they can be seen in the images.
![image](https://user-images.githubusercontent.com/2675655/106334258-575b8280-629b-11eb-9edf-b879ad1a6cf8.png)![image](https://user-images.githubusercontent.com/2675655/106334244-51fe3800-629b-11eb-8234-ce7082e36451.png)
I have a this motherboard https://www.gigabyte.com/Motherboard/GA-AB350-Gaming-3-rev-1x/sp#sp

**Comment by LiloBzH** [comment]
Same here

MSI B550 Edge Wifi

**Comment by sinancetinkaya** [comment]
with the commit of 249c4c8 , network card disappears completely, instead of duplicating.

**Comment by sinancetinkaya** [comment]
@sebastian-dev with the commit of 249c4c8 , network card disappears completely, instead of duplicating.
