### ISSUE TITLE
Incorrect fan sensor detection EX-A320M-GAMING

### ISSUE THREAD

**Issue by cremilton** [LibreHardwareMonitor/LibreHardwareMonitor#389]
Fan1 is CPU (21RPM?);
Fan2 is CHA_FAN (not fan connected);
Fan3 is AIO_PUMP.

![libremonitor](https://user-images.githubusercontent.com/3596949/107783809-6a556480-6d29-11eb-9497-50937df76455.PNG)

Thanks for the great working.

After the execution of HWMonitor, the reading of the sensors is correct. 

![libre-correct](https://user-images.githubusercontent.com/3596949/107786535-ca99d580-6d2c-11eb-8690-e8f5b66b04d9.PNG)

**Comment by riQQ** [comment]
See also #277

**Comment by PhyxionNL** [comment]
Closing in favor of #277.
