### ISSUE TITLE
Add support for external coolant temperature sensor

### ISSUE THREAD

**Issue by ahodges-git** [LibreHardwareMonitor/LibreHardwareMonitor#401]
I have a coolant temperature sensor that plugs into a 2 pin header (T_Sensor) on my Asus Crosshair VIII Impact motherboard.

I'm keen to see if this can be supported so I can make use of it in https://github.com/Rem0o/FanControl.Releases

Motherboard manual:
![image](https://user-images.githubusercontent.com/80186464/110416583-b1900480-80df-11eb-8078-ca1ba1928b59.png)

Appears in HWiNFO64:
![image](https://user-images.githubusercontent.com/80186464/110416603-b9e83f80-80df-11eb-957f-12a402fd93aa.png)

**Comment by stevepositiv** [comment]
I have the same issue on my ROG X570-I.

@contributors: Is there any way I could help to get this sensor readable?

**Comment by Ja50n-Kru** [comment]
As seen in HWiNFO 64, that sensor is on the ASUS EC chip - see issue #282

**Comment by PhyxionNL** [comment]
> 
> 
> As seen in HWiNFO 64, that sensor is on the ASUS EC chip - see issue #282

Closing this in favor of that.
