### ISSUE TITLE
When i put RTX 3060 on top of the RTX 2070 Wronge Memory Read

### ISSUE THREAD

**Issue by DanityBG** [LibreHardwareMonitor/LibreHardwareMonitor#416]
I was with 1 card RTX 2070 and last week i buy RTX 3060 and when i put it on my pc  program show on the 2 cards only the RTX 3060 memory total  VRAM 12 gb .I try some stuff  and when i make in BIOS CSM Support VRAM of 2070 came and show 8 gb  but Resizebla BAR is not supported. I turn off CSM option in bios and again 12 gb VRAM on RTX2070.

**Comment by PhyxionNL** [comment]
These values are returned by NVIDIA's API, there's nothing possible there I think.
