### ISSUE TITLE
Support for 11th Gen i7-11700k CPU Temps

### ISSUE THREAD

**Issue by Bruro** [LibreHardwareMonitor/LibreHardwareMonitor#420]
Hello there!
I know, the release of the 11th gen was just about a week ago but I still wanted to point out, that the CPU temps are missing. (At least on the i7-11700k)

**Comment by PhyxionNL** [comment]
This'll be fixed by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/421 once merged.

**Comment by PhyxionNL** [comment]
Merged, so closing this.
