### ISSUE TITLE
GPU Manufacturer name appears twice in IHardware.Name

### ISSUE THREAD

**Issue by Pomianowski** [LibreHardwareMonitor/LibreHardwareMonitor#451]
## The name of the graphics card manufacturer appears twice for Nvidia.
After updating to the latest snapshot (0.8.8-189), the manufacturer's name appears twice, I don't know where to find the source of this problem.

#### In my application
![image](https://user-images.githubusercontent.com/13592821/119255776-c9930280-bbbd-11eb-9a04-b2aa62a958a1.png)

#### In LibreHardwareMonitor Report
![image](https://user-images.githubusercontent.com/13592821/119255808-f47d5680-bbbd-11eb-8c74-58e411a21f0d.png)

**Comment by PhyxionNL** [comment]
You're right, I can reproduce this. I have fixed it.
