### ISSUE TITLE
How to override default behavior and set fan speed permamently even after close program (and with c# with LibreHardwareMonitor lib)

### ISSUE THREAD

**Issue by AndNovAtor** [LibreHardwareMonitor/LibreHardwareMonitor#457]
Is it possible to ignore "safe close" and leave the fan speed to the one I manually set in GUI?

Also, for example, if I use example code from README and set fan speed:
`if (sensor.Name == "Fan Control #3") {
    sensor.Control.SetSoftware(40);
}`
after console program ends fan speed returns to "default"

(I want to set speed for a chassis fan)

For example, when I set manual speed in SpeedFan and close it, it doesn't do "safe close" and my fan speed remains the same (as I want for a chassis fan)

[P.s. - my "old" ASUS P8Z77-V LX motherboard only can set 60% speed as minimum speed]

**Comment by PhyxionNL** [comment]
This is not possible, almost everything is reset to default once you close it. You can choose not to close "Computer" on close to prevent that.
