### ISSUE TITLE
little correction in AMDK17.CS UpdateSensor

### ISSUE THREAD

**Issue by rmattuschka** [LibreHardwareMonitor/LibreHardwareMonitor#47]
_coreTemperatureTctl.Value = (temperature * 0.001f);
         _coreTemperatureTdie.Value = (temperature * 0.001f) + offset;
must be:
        _coreTemperatureTctl.Value = t;
        _coreTemperatureTdie.Value = t + offset;

**Comment by Phyxion** [comment]
Yes, that makes sense. Feel free to submit a PR and I'll accept it 👍

**Comment by Phyxion** [comment]
Fixed by #48.
