### ISSUE TITLE
Vega 11 GPU crazy load readings

### ISSUE THREAD

**Issue by Dag776** [LibreHardwareMonitor/LibreHardwareMonitor#49]
Hi

I have a small piece of software I use to monitor my Plex server and after migrating from Intel to a new AMD based server I have large issues with sensor readings as I was using the latest OHM DLL library. After discovering Libre fork, it looks like I'll have temp readings on the Ryzen 2400G CPU part if I figure out how to read them opposed to Intel, but I'm missing GPU info. There's no temp, and the load is crazy.

![vega11crazyloadreadings](https://user-images.githubusercontent.com/41741107/43262056-1469f1f4-90df-11e8-9ebd-9b338204c335.png)

HWiNFO seems to read temp and load fine from Vega11. I've contacted them about access to a DLL I can use but I don't have my hopes up.

**Comment by Phyxion** [comment]
LHM uses the AMD APIs (ADL is the name of it) for reporting the voltages and stuff, I don't have a Vega to test, but you might be able to test it debug yourself  https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/tree/master/Hardware/ATI 
It's pretty straightforward all in all I think. It's also possible that there's a driver bug, have you tried another driver version for it? 
You're unlikely to get HWiNFO dll, it's purchasing only. You might be able to use HWiNFO's executable's shared memory, but you'd have to either reverse engineer that yourself or ask them for details.

**Comment by Dag776** [comment]
Thanks, I'll experiment a little and report back if I get it working.

**Comment by Phyxion** [comment]
This has all been changed now, closing, please open a new issue if it still persists.
