### ISSUE TITLE
Add Nvidia Hot Spot sensor

### ISSUE THREAD

**Issue by Keltere** [LibreHardwareMonitor/LibreHardwareMonitor#498]
Hi, as the title, just requesting the implementation of the hot spot sensor for nvidia graphic cards.
Thanks.

**Comment by JustAMan** [comment]
See this: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/440#issuecomment-885587001

**Comment by Keltere** [comment]
Double of https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/440#issuecomment-885587001
