### ISSUE TITLE
Console version for Zabbix

### ISSUE THREAD

**Issue by Dozentz** [LibreHardwareMonitor/LibreHardwareMonitor#526]
Tell me how to make a console version and output data to the console via bat for using Zabbix
Example
@echo off
for /F "usebackq tokens=7-10" %%a in (`C:\LibreHardwareMonitor\LibreHardwareMonitorReport.exe`) do echo %%b %%c %%d| find "/intelcpu/0/temperature/4">nul && set temper=%%a 
echo %temper%

**Comment by PhyxionNL** [comment]
Please use discussions for this.
