### ISSUE TITLE
SDK throwing exception at NvAPIWrapper.Native.GPUApi.GetCoolerSettings 

### ISSUE THREAD

**Issue by Snazzie** [LibreHardwareMonitor/LibreHardwareMonitor#528]
Im running a 3080ti if thats any help. 

### exception
NvAPIWrapper.Native.Exceptions.NVIDIAApiException
  HResult=0x80131500
  Source=NvAPIWrapper
  StackTrace:
   at NvAPIWrapper.Native.GPUApi.GetCoolerSettings(PhysicalGPUHandle gpuHandle, CoolerTarget coolerTarget)

### message
NVAPI_NOT_SUPPORTED

**Comment by PhyxionNL** [comment]
Fixed by #553
