### ISSUE TITLE
Incorrect data of GPU memory (GeForce 9600 GT)

### ISSUE THREAD

**Issue by FanIT** [LibreHardwareMonitor/LibreHardwareMonitor#564]
Hi. In latest update LibreHardwareMonitorLib 0.8.9-pre43 incorrect to display GPU memory used and free. And the values don't change any more.
Build from source code.
![LHM](https://user-images.githubusercontent.com/20283004/135412573-350c5665-e978-42b4-a249-75885c055b1b.PNG)
Latest stable release.
![0 8 8](https://user-images.githubusercontent.com/20283004/135413748-c805809d-4cae-490e-b900-f4a06f87e991.PNG)

**Comment by PhyxionNL** [comment]
Thank you for the report, I can confirm this problem. I have a fix ready 👍
