### ISSUE TITLE
Windows 11 : WMI doesn't work anymore

### ISSUE THREAD

**Issue by Raphyyyy** [LibreHardwareMonitor/LibreHardwareMonitor#581]
Hello,

Since I have upgraded to windows 11, WMI query don't work anymore. The namespace is detected (maybe an old history) and when I am trying to execute a query (select * from sensor), it computes nothing.. No error message nothing...

Can you guys tell me what to do or can you fix the issue please ?

Thanks !

**Comment by PhyxionNL** [comment]
Tested on three W11 machines here and still works fine.
