### ISSUE TITLE
Win 11: CPU freq to high when HVCI is enabled

### ISSUE THREAD

**Issue by swiffer** [LibreHardwareMonitor/LibreHardwareMonitor#582]
When enabling HVCI in Windows 11 CPU freq in OhmGraphite (which is based on LibreHardwareMonitor) is way to high (20-40Ghz). Can this be confirmed by someone?

Sys-Specs: Win11 22000.282, Ryzen R9 5900X

![grafik](https://user-images.githubusercontent.com/2990373/138591884-1896d02e-268d-49a9-aba3-b1fcbddefa05.png)

**Comment by PhyxionNL** [comment]
Duplicate of #566
