### ISSUE TITLE
12th Gen Intel Core i9-12900 can't get temperature

### ISSUE THREAD

**Issue by Quttia** [LibreHardwareMonitor/LibreHardwareMonitor#588]
![2021-10-29 111250](https://user-images.githubusercontent.com/26808114/139371035-5c824054-26a3-4de1-bf49-3472d06477f8.png)
[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/7438681/LibreHardwareMonitor.Report.txt)

**Comment by sebastian-dev** [comment]
try out this: https://github.com/sebastian-dev/LibreHardwareMonitor/releases/tag/AlderLake
