### ISSUE TITLE
Antivirus Warning

### ISSUE THREAD

**Issue by enzovic** [LibreHardwareMonitor/LibreHardwareMonitor#590]
Bitdefender warned me that LibreHardwareMonitorLib.dll is infected with Gen: Suspicious.Cloud.4.Nm8@aWrXpAp and has been quarantined. 
I tried to install again, but when unzipping it suffers the same thing.

**Comment by FanIT** [comment]
I have send a ticket about false positive in support of Bitdefender.
I have a detecting at beta, but the detect is other.

**Comment by PhyxionNL** [comment]
Closing, this should be addressed by the AV.
