### ISSUE TITLE
The plot doesn't look right, possibly due to display scaling

### ISSUE THREAD

**Issue by VioletGiraffe** [LibreHardwareMonitor/LibreHardwareMonitor#6]
![image](https://user-images.githubusercontent.com/1175926/30313894-99ab8080-97a7-11e7-8e98-6eb5e0110f45.png)

This looks wrong, aside from the fact that nothing is actually being plotted (maybe I just don't understand how to use this feature). And no, the screenshot isn't truncated, this is the whole plot window captured with Alt+PrtScr. This on a 4K monitor with 175% scaling; it could be that the scaling is the reason for the truncated "0:00" label. Just a guess.

**Comment by Maddimax** [comment]
Once you have opened the Plot, there are checkboxes next to each Sensor in the main menu. Check those to get stuff into the Plot.

**Comment by Maddimax** [comment]
I cannot reproduce the issue with the truncated 0:00. ( I tried 125%, 150% and 175% scaling ). 
Can you check whether the plot is also cropped if you choose on of the other options under "Menu=>Options=>Plot Location"

**Comment by VioletGiraffe** [comment]
Yes, it is truncated with all those options.
