### ISSUE TITLE
OxyPlot exception in plot window

### ISSUE THREAD

**Issue by JoeBroesele** [LibreHardwareMonitor/LibreHardwareMonitor#637]
This OxyPlot exception message is shown every few seconds in the plot window:

![OxyPlot exception](https://user-images.githubusercontent.com/56547187/150644739-7b9c1a3e-257d-4b72-8791-d7671ad1f361.png)

Clearing the history data from ```LibreHardwareMonitor.config``` seems to fix the issue for some time, but then it reappears.

**Comment by PhyxionNL** [comment]
Thanks, merged.
