### ISSUE TITLE
Identifying Sensors for Asus Crosshair VIII Hero (WiFi)

### ISSUE THREAD

**Issue by WanaGo** [LibreHardwareMonitor/LibreHardwareMonitor#646]
Hi, Came across this library after being directed to FanControl.

Asus Crosshair VIII Hero (WiFi) Motherboard
5950X Processor

Installed V102 of Fan Control, and it found my fans etc, and sensors, but I cant match the Motherboard sensors it found with anything from HWInfo to try and figure out what they are.
I was ideally looking for T-Sensor, but reading other issue posts I am not sure that one is available. This is what my water loop is connected to for GPU and CPU, into 2 Rads (6 fans), so that is a bit sad that it doesnt appear to be supported.

I have been using Argus Monitor and that supports T-Sensor, but FanControl was more specific as to what I needed to do without monitoring lots of stuff I didn't.

Can someone help identify what these sensors are?

![image](https://user-images.githubusercontent.com/759846/152146925-ce65ea1d-4ebb-41c8-b89c-dc26d50ca011.png)

Thanks in Advance

**Comment by zeule** [comment]
Can this be closed now?
