### ISSUE TITLE
.NET 4.5.2 base assemblies are not available in VS 2022

### ISSUE THREAD

**Issue by zeule** [LibreHardwareMonitor/LibreHardwareMonitor#650]
...and need to be installed separately, but this target is set as default for the executable. Is it possible to migrate to a newer version, please? 4.7.2 is fine.

**Comment by PhyxionNL** [comment]
Yes, I agree. Lets bump it to 47, which seems to be installed by default (at least it's installed here along with 471 and 472).

**Comment by zeule** [comment]
Thanks!

**Comment by zeule** [comment]
@PhyxionNL, was there a reason to choose 47 over 472?

**Comment by PhyxionNL** [comment]
> @PhyxionNL, was there a reason to choose 47 over 472?

Updated to 472 :)

**Comment by zeule** [comment]
Thank you!
