### ISSUE TITLE
[Fan Control] No fan control on Gigabyte Z690 Aorus Elite DDR4

### ISSUE THREAD

**Issue by Zarco92** [LibreHardwareMonitor/LibreHardwareMonitor#669]
Ever since upgrading to a 12700K + Gigabyte Z690 Aorus Elite DDR4, I haven't been able to control any fans connected to the motherboard via Fan Control. Fan control for my RTX 3080 works fine. Afaik, hardware compatibility issues are entirely dependant on these libraries so I'll report it here.

Running the latest release of Fan Control (103) with the latest LibreHardwareMonitor update, on Windows 11.

**Comment by zokradonh** [comment]
Please post your LibreHardwareMonitor.Report.txt that can be generated with the LibreHardwareMonitor application.
I have the Gigabyte Z690 Aorus Pro DDR5 and also same problems. I am currently trying to fix it.

**Comment by Zarco92** [comment]
Will do ASAP, thanks

**Comment by zokradonh** [comment]
Ok, your mainboard also uses IT8689E like my mainboard. So it will work once I have finished #672

**Comment by Zarco92** [comment]
Damn, that's great. Let me know if you need something else. Should I close this issue now? I'm kinda new to github.

**Comment by zokradonh** [comment]
You can close this issue once it really works for you.

**Comment by Zarco92** [comment]
Alright. Thanks again!

**Comment by Zarco92** [comment]
Forgot to close this one, sorry about that.
