### ISSUE TITLE
Virus Total Scan Flagged

### ISSUE THREAD

**Issue by Snazzie** [LibreHardwareMonitor/LibreHardwareMonitor#675]
https://www.virustotal.com/gui/file/d67126c7803912691303530900219e6230ee93447d4a58260252d8088d93ebd2?nocache=1
Hi, `LibreHardwareMonitorLib.dll` got flagged by one vendor with `HackTool.VulnDriver!1.D7DD (CLASSIC)`

Are you aware of this? If it is false positive, do you know the reason?

**Comment by PhyxionNL** [comment]
It's a false positive for one questionable AV. All proper ones don't detect it.
