### ISSUE TITLE
Samsung PM9A1 support

### ISSUE THREAD

**Issue by shenqiushi** [LibreHardwareMonitor/LibreHardwareMonitor#685]
Hi, I'm using Samsung PM9A1, it can't be identified by LHM. Do we have plan to add support for this device？

Thanks~

**Comment by PhyxionNL** [comment]
This should work correctly in latest build.

**Comment by PhyxionNL** [comment]
That's not the latest build but the latest release 🙂
You can download the latest builds here:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions
Click on a workflow run on **master** (right now the latest is **Sync EC implementation to the Linux driver**), then download **LibreHardwareMonitor-net472**.
