### ISSUE TITLE
How much this fork is ahead of the official OHM in terms of hardware support?

### ISSUE THREAD

**Issue by Joni-Salminen** [LibreHardwareMonitor/LibreHardwareMonitor#7]
Hi! As title says is this fork ahead of the official OHM project in terms of hardware support?
I'm building fan control app, mostly to get inbuilt support for my custom fan control hardware, without having to have separate app for that and motherboard fan connectors.

I'm still kinda if newbie developer so making bigger changes take some time for me, which is why I don't just "test" this, but rather ask.

**Comment by Phyxion** [comment]
Yes, it's a signifcantly ahead of OHM as all hardware PRs have been merged.
