### ISSUE TITLE
NIC UL/DL Speed fixed to high negative values (after sleep / wakeup?)

### ISSUE THREAD

**Issue by Eno77** [LibreHardwareMonitor/LibreHardwareMonitor#72]
My Ethernet UL/DL speeds are at fixed values
UL at -69010,9kb/s
DL at -533863,9 kb/s

I suspect hybernate / energy save may be the trigger (close Laptop lid -> energy save, reopen again)
![grafik](https://user-images.githubusercontent.com/33687620/50015017-c98e8180-ffc5-11e8-887c-ffa14471991d.png)

**Comment by Eno77** [comment]
A second (maybe related) issue:
It seems, that the NIC are enumerated again at each start and the "show in gadget" mark is not there anymore since the order is not the same for each Enumeration?

**Comment by nickbabcock** [comment]
Good spot, I can confirm that network reporting has faulty values after wake up. I have a fix in the pipeline
