### ISSUE TITLE
Gigabyte X570 Aorus Master - ITE IT8792E - No controls

### ISSUE THREAD

**Issue by Gucioo** [LibreHardwareMonitor/LibreHardwareMonitor#731]
This motherboard has 2 IO chips:
- for 1st one sensors and controls are present
- for 2nd there are only sensors, no controls: Fan 4, 5 & 6.

 It's a ITE IT8792E. How support for this could be added?

![image](https://user-images.githubusercontent.com/7483436/166260705-e7723c55-84cf-43dc-8148-58826b2d121c.png)

**Comment by Dirkxke** [comment]
The X570 Aorus Pro uses the same controller for the same fans.
2 birds 1 stone?

**Comment by kybdi** [comment]
I am having the same issue as described, where the second group of sensors is being ignored by fan controls.

![image](https://user-images.githubusercontent.com/27274992/173223715-3399de0d-5bfe-4212-914e-44c0a3ab25c6.png)

Aorus X570 Extreme is my motherboard, looks like the value is showing as it8792e/it8795e

I am unsure if adding just one will fix this issue, so if possible (assuming they are closely related, could support for t8792e AND it8795e be added?

**Comment by mrehkopf** [comment]
Same issue here with X570S AORUS MASTER, I can read and control the fans on the IT8689E.

But the Fan Controls on the IT8695E act as if they are read only.
The RPM control setting seems to reflect the current setting on the controller (66%) but I cannot change it.
When I stop the fan by hand the Fan RPM reading (Fan #3) changes accordingly.


![image](https://user-images.githubusercontent.com/238664/178221581-a49b0d9a-20b6-4f99-b77a-c7df40efe2bb.png)

**Comment by slhad** [comment]
I got a X570 Aorus Pro and I have also no control of the 3 fans attached to ITE IT8792E/IT8795E like everybody here

**Comment by slhad** [comment]
Seems like there is an old issue with new comments on it referencing the problem #251
Apparently ITE IT8792E/IT8795 controllers rewrite the old control value of the bios just after the user change it

Feel like it will be quicker to change the motherboard than have some sort of update of bios/drivers that fix this weird behavior

**Comment by severgun** [comment]
> Apparently ITE IT8792E/IT8795 controllers rewrite the old control value of the bios just after the user change it
> Feel like it will be quicker to change the motherboard than have some sort of update of bios/drivers that fix this weird behavior

I have Gigabyte Z690 PRO with 8695 that behave same way. Read PWM % but not set. Gigabyte SIV software can control it, so I would say that it is not BIOS issue.
Seems like whole https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/IT87XX.cs just a mess. Should be error with registers or values somewhere.
To be fair I can't find datasheets for most of ITE products.

**Comment by PhyxionNL** [comment]
See #731.

**Comment by BobC0728** [comment]
Any hope for this?  Also an Aorus Master X570S MB.  Seems like it has been an issue for two years plus.
