### ISSUE TITLE
Incorrect reading from ASUS TUF B450-PRO GAMING (ITE IT8665E)

### ISSUE THREAD

**Issue by CovenantSquad** [LibreHardwareMonitor/LibreHardwareMonitor#737]
Hi, 
first of all, thanks for all of your work in this project.
LibreHardwareMonitor is reading wrong temperature and fan speed values from my B450-PRO (ITE IT8665E); in fact FanControl, which uses this library to read temperatures and set fan speeds, is not able change any of the attached fans' speed.
It seems like both LibreHardwareMonitor and FanControl work correctly when CPUID HWMonitor is (or has been) running.
![Screenshot (36)](https://user-images.githubusercontent.com/84512066/167247038-4b4a5bf4-a29b-4275-bcdf-5a18e7fb0922.png)
![Screenshot (37)](https://user-images.githubusercontent.com/84512066/167247056-398c1aef-a647-4d48-a308-4d82b69408f7.png)

**Comment by Svek** [comment]
I'm looking into all these ASUS board related issues and particularly this statement you are making
> [works] correctly when CPUID HWMonitor is (or has been) running.

I saw a few other threads about this in other parts of the internet, and I have a hunch this has to do with permissions and potentially some outdated or bugged code from OpenHardwareMonitor (where a good portion of the underlying code that LHW relys on to "just work").

**Comment by Svek** [comment]
A quick update... I've added some code to get into this issue further.
Some triage and a bit more testing might be needed.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/758

**Comment by CovenantSquad** [comment]
That's awesome, Thanks!
