### ISSUE TITLE
Documentation req, Needs 64Bit build target

### ISSUE THREAD

**Issue by MangyDogUK** [LibreHardwareMonitor/LibreHardwareMonitor#772]
Ok I just spent several days trying to figure out why I couldnt get full data read outs from the API, Specifically GPU Package data (wattage) It just wouldnt show up. I went though the example app line by line and really couldnt figure it out, till i saw in the discussion some one mentioning 32Bit targets.

I checked my project and it indeed was set to 32Bit. Changing this to 64Bit worked and I could get all the data I needed. 

Documentation request. 
Please clearly state the API needs 64Bit build target to fully work.

And could we also get some actual documentation? or have the example program have detailed comments? 
It really was a chore going through everything for what really should have been such a simple fix, if I had something to read on it.

**Comment by PhyxionNL** [comment]
It doesn't need 64-bit; you need to target Any CPU or native OS arch. You just cannot use 32-bit on 64-bit (or 64-bit on 32-bit).
