### ISSUE TITLE
Cannot access CPU temperature on intel 12th gen processor.

### ISSUE THREAD

**Issue by liblaf** [LibreHardwareMonitor/LibreHardwareMonitor#776]
Cannot access CPU temperature on intel 12th gen processor.

**Comment by frankfoxy** [comment]
Not work for me on 12700H
![image](https://user-images.githubusercontent.com/7473093/178775666-4d259c25-dd6f-416f-8a51-5e87536457fd.png)

**Comment by DevTechProfile** [comment]
Please post a CPU-Z screenshot. This is Alder Lake-H, there is a problem with a missing model ID.

**Comment by DevTechProfile** [comment]
Created PR  #779.

**Comment by liblaf** [comment]
Not work for me on i7-1260P

![image](https://user-images.githubusercontent.com/30631553/179077251-e40f8513-c68a-4d44-856b-fdfdb464e21d.png)

![image](https://user-images.githubusercontent.com/30631553/179076867-33274520-3a84-4ad5-a5c2-3bbaf851ddc3.png)

**Comment by DevTechProfile** [comment]
> Not work for me on i7-1260P

I've added model ID 9A to the switch-case-block, see link to PR above.

**Comment by PhyxionNL** [comment]
Done 👍
