### ISSUE TITLE
Is there any way to output JSON data on the command line or just start the server? 

### ISSUE THREAD

**Issue by LRF520** [LibreHardwareMonitor/LibreHardwareMonitor#809]
Is there any way to output JSON data on the command line, or just start the server? Because the GUI interface consumes too much CPU, it always occupies 13% of the CPU. In many cases, JSON data is enough, and it is not necessary to start the GUI.

![image](https://user-images.githubusercontent.com/58470642/187878260-c1bec908-c4c3-49a0-b59c-82f9cc3e3e3b.png)

**Comment by JohnTravolski** [comment]
I use python to grab it

**Comment by LRF520** [comment]
> I use python to grab it
> 
> ```
> from urllib.request import urlopen
> import json
> mylink = f'http://{ip}:8085/data.json'
> pagesource = urlopen(mylink).read().decode('utf-8')
> alldata = json.loads(pagesource)
> ```

It still needs to start the whole GUI before it can grab JSON data. Is there a way to start only the server now?

**Comment by JohnTravolski** [comment]
I am not sure. I have a Windows task to run it at Windows startup and I have it set to be minimized to tray by default.

![image](https://user-images.githubusercontent.com/36255053/189275582-eac508d9-cfd6-490e-a242-081afbefa4f3.png)

**Comment by LRF520** [comment]
> I am not sure. I have a Windows task to run it at Windows startup and I have it set to be minimized to tray by default.
> 
> ![image](https://user-images.githubusercontent.com/36255053/189275582-eac508d9-cfd6-490e-a242-081afbefa4f3.png)

It always occupies 13% of the CPU,reducing CPU consumption is the problem I want to solve at present.
