### ISSUE TITLE
12th generation Intel CPU can not get temperature

### ISSUE THREAD

**Issue by MuggleTan** [LibreHardwareMonitor/LibreHardwareMonitor#811]
Hello, I use the 12th Intel i7-12700 CPU and Windows11, but the software can't get the temperature of the CPU.
![image](https://user-images.githubusercontent.com/50989379/189485966-53ff7fe4-1c49-4dad-9b85-9a2af661cbba.png)

**Comment by severgun** [comment]
Maybe H related
![8foxDtu26j](https://user-images.githubusercontent.com/1197314/189493250-6a8ff779-f931-4fee-a59d-f9d354055b52.png)

**Comment by iophobia** [comment]
No temps here on an i5-1240P either. Win 10 Pro w/ LHM 0.9.0

**Comment by PhyxionNL** [comment]
Can you attach a report? File > Save Report.

**Comment by iophobia** [comment]
Sure, here you go. [LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/9564634/LibreHardwareMonitor.Report.txt)
