### ISSUE TITLE
Cannot access CPU temperature on 12th Gen Intel Core i7-12700F

### ISSUE THREAD

**Issue by HackHarry** [LibreHardwareMonitor/LibreHardwareMonitor#813]
![image](https://user-images.githubusercontent.com/27217566/189535133-2a480e7e-39ba-4b82-8f2a-9f796184c64b.png)

**Comment by BlueTalon6** [comment]
If you scroll down, in temperatures is there "CPU package" under "CPU Core #12"?

**Comment by HackHarry** [comment]
Yes, it is.
![image](https://user-images.githubusercontent.com/27217566/189903306-6951300c-d5bf-4b4e-abbb-b603e7d23dac.png)

**Comment by BlueTalon6** [comment]
Sorry, I thought you were looking for the sensor, didn't notice your values were blank. 
I notice there is no chip listed under your motherboard and no sensors listed so I suspect it is not recognised or doesn't provide the necessary readouts

**Comment by PhyxionNL** [comment]
Can you attach a report? File > Save Report.

**Comment by sebastian-dev** [comment]
https://github.com/torvalds/linux/blob/master/arch/x86/include/asm/intel-family.h
#define INTEL_FAM6_ALDERLAKE		0x97
#define INTEL_FAM6_ALDERLAKE_L 0x9A
#define INTEL_FAM6_ALDERLAKE_N		0xBE

#define INTEL_FAM6_RAPTORLAKE		0xB7
#define INTEL_FAM6_RAPTORLAKE_P		0xBA
#define INTEL_FAM6_RAPTORLAKE_S		0xBF

**Comment by PhyxionNL** [comment]
Thanks @sebastian-dev, PR #815.
