### ISSUE TITLE
13th Gen Intel Core i9-13900KF can't get temperature

### ISSUE THREAD

**Issue by Quttia** [LibreHardwareMonitor/LibreHardwareMonitor#857]
[HardwareReport.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/9856297/HardwareReport.txt)

**Comment by MGD4096** [comment]
run app as administrator

**Comment by Aytackydln** [comment]
It is definitely not about administrator privilage. Project-Aurora runs as admin and users with same cpu have this problem, too.

**Comment by MGD4096** [comment]
In my case, I needed administrator privileges to see the CPU temperatures.

[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/9992880/LibreHardwareMonitor.Report.txt)

**Comment by Quttia** [comment]
The LibreHardwareMonitorLib.dll version I used in this issue was 0.9.0, now I upgrade to 0.9.1, problem solved. Thanks all.
