### ISSUE TITLE
Can LibreHardwareMonitorLib target .NET Standard2.0 to .Net Framework 4.6.1 project?

### ISSUE THREAD

**Issue by asdf130162** [LibreHardwareMonitor/LibreHardwareMonitor#860]
I tried to import .Net Framework 4.6.1 an error occurred.
![image](https://user-images.githubusercontent.com/38516259/198209718-413b63ae-3c2d-41c3-8212-128027875dc1.png)

![image](https://user-images.githubusercontent.com/38516259/198210476-bb53e7a8-f41b-4d5d-9ea7-6d4fe8a24544.png)

Error Info : 
System.IO.FileNotFoundException: ' Could not load file or assembly or one of its dependencies  "System.IO.FileSystem.AccessControl, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a” '.

**Comment by PhyxionNL** [comment]
Upgrade your .NET version. .NET 4.6.1 is out of support.
