### ISSUE TITLE
Please don't drop .NET Standard

### ISSUE THREAD

**Issue by PrzemyslawKlys** [LibreHardwareMonitor/LibreHardwareMonitor#870]
Could you not DROP .NET Standard
- https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/ecc6b6a6a706e2b2066319ed8e92d399ff0c16f2

I use your library in Windows PowerShell and PowerShell 6 and PowerShell 7. NET Standard is the only way to cover all 3 under one DLL. While I understand that .NET has moved on but NET Standard 2.0 is still fully supported.

**Comment by PhyxionNL** [comment]
I've brought this back for now 🙂
