### ISSUE TITLE
WindowsStorage Exeption, AccessViolationException

### ISSUE THREAD

**Issue by sebastian-dev** [LibreHardwareMonitor/LibreHardwareMonitor#907]
`
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at System.SpanHelpers.IndexOfNullByte(Byte ByRef)
   at System.String.Ctor(SByte*)
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr)
   at LibreHardwareMonitor.Hardware.Storage.WindowsStorage+StorageInfo.GetString(IntPtr, UInt32)
`

Possible fix:
`
[HandleProcessCorruptedStateExceptions]
        [SecurityCritical]
        private static string GetString(IntPtr descriptorPtr, uint offset)
        {
            try
            {
                return offset > 0 ? Marshal.PtrToStringAnsi(IntPtr.Add(descriptorPtr, (int)offset))?.Trim() : string.Empty;
            }
            catch (AccessViolationException)
            {
                return string.Empty;
            }
        }
`
Currently i cant test this.

Is a better than cast to Int64
`
IntPtr.Add(descriptorPtr, (int)offset)
`

**Comment by PhyxionNL** [comment]
Those attributes are ignored in .NET Core, but I have changed it to IntPtr.Add.
