### ISSUE TITLE
GpuNvidia is missing in Windows Forms Application (C#)

### ISSUE THREAD

**Issue by CaptainAlekor** [LibreHardwareMonitor/LibreHardwareMonitor#930]
GpuNvidia is missing in Windows Forms Application (C#). On a screenshot i ran same code, but one in console app and the other in Windows Forms application (Visual Studio, C#). You can notice, that there are no "Hardware: NVIDIA GeForce RTX 3050 Ti Laptop GPU" in Windows Forms app. What is the problem, how can i fix it?
![изображение](https://user-images.githubusercontent.com/79224183/207460921-2fc2c20e-a74d-428b-b634-d0d5373a8da7.png)

**Comment by CaptainAlekor** [comment]
Solved: setting solution platform to x64 fixed the problem.
![изображение](https://user-images.githubusercontent.com/79224183/207465493-23623df4-b446-42b9-99b6-bc753cfbc4f0.png)

**Comment by JunSourceX** [comment]
> Solved: setting solution platform to x64 fixed the problem. ![изображение](https://user-images.githubusercontent.com/79224183/207465493-23623df4-b446-42b9-99b6-bc753cfbc4f0.png)

Thank you, you helped me)
