### ISSUE TITLE
LibreHardwareMonitor not displaying GPU temperature but Open Hardware Monitor can for the same GPU

### ISSUE THREAD

**Issue by odopo** [LibreHardwareMonitor/LibreHardwareMonitor#948]
I have a laptop with an Intel UHD Graphics 620 and a Radeon 540 Graphics. Open Hardware Monitor shows temperature and other info like core voltages, clocks & GPU fan info for Radeon 540 Graphics that LibreHardwareMonitor doesn't show. Could you please at least add temperature info for this GPU?

![image](https://user-images.githubusercontent.com/100270166/210537408-fb439485-bc8a-4d78-8c78-76d404b97323.png)

[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/10343327/LibreHardwareMonitor.Report.txt)
[OpenHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/10343328/OpenHardwareMonitor.Report.txt)

Edit: I just noticed that the report generated by LibreHardwareMonitor includes these information but the application doesn't show it. Can it be shown in the application?

**Comment by cl0rm** [comment]
Same for 6900XT (AsRock). 
OpenHardwareMonitor 0.9.2 works.
Even Report does not include the Temps

**Comment by PhyxionNL** [comment]
Please attach reports from both versions, the one that works and latest LHM. I can take a look.
