### ISSUE TITLE
Can't Access Temperature Data on Intel Core i9-12900H

### ISSUE THREAD

**Issue by kzettlmeier** [LibreHardwareMonitor/LibreHardwareMonitor#966]
Looks like the values for Temperatures are blank for the CPU.  You can find the report attached.
[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/10669033/LibreHardwareMonitor.Report.txt)

**Comment by kzettlmeier** [comment]
![image](https://user-images.githubusercontent.com/3236828/217081530-1df4e8ff-9ca8-4225-bc61-e570a4c2d37d.png)

**Comment by atomo33** [comment]
In my case Avast said LibreHardwareMonitorLib.sys (LibreHardwareMonitorLib.dll) is as an unsafe driver and disabled it. Thus no more Temperature monitoring for me.

**Comment by Drew221** [comment]
Yea Avast One blocked it and the old Open Hardware Monitor for me too. Not sure how to get around it.

**Comment by atomo33** [comment]
In my case, (again), I disable the new Avast driver protection, then I run LibreHardwareMonitor, and then I enable the Avast protection again.

**Comment by PhyxionNL** [comment]
#984

**Comment by kzettlmeier** [comment]
To be clear, I am not using Avast.

**Comment by PhyxionNL** [comment]
Ah, but it's related to Ring0, from your report:

Status: Installing driver "LibreHardwareMonitor.sys" failed and file exists

Perhaps you're running something else that uses WinRing0?

**Comment by kzettlmeier** [comment]
@PhyxionNL everything seems to work fine in that build now!  Thanks and sorry for the late response!
