### ISSUE TITLE
Sensor/control detection fails on Asrock Z790 PG/ITX and FanControl

### ISSUE THREAD

**Issue by NewbieOnPractice** [LibreHardwareMonitor/LibreHardwareMonitor#990]
Since the latest release of LHM lib (0.9.1) FanControl isn't able to read the sensor/control information from my Asrock Z790 PG/ITX anymore. The problem might relate to this change:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/af0f4b696bb48074305153773f4ec3e633e68604#diff-ab954123283065b240cec0d9311bd2feffade5803136f44cfe7d89242a81373a

Original thread on the FanControl discussion board:
https://github.com/Rem0o/FanControl.Releases/discussions/1577

Rolling back to the previous LHM lib version (which btw. is also 0.9.1) fixed the problem and made FanControl work again.

**Comment by PhyxionNL** [comment]
This is fixed by #999, closing.
